# Five additional FAQ pairs per page for Total Town Car Service.
# Keyed by page file. Consumed by the static-site page generator alongside the
# spec files; this file never edits them. Plain text answers, 30-70 words each,
# written to be quoted directly by answer engines.

EXTRA = {

    # ---------------------------------------------------------------- services A

    'msp-airport-black-car-service.html': [
        ("What time should my car pick me up for a departing flight at MSP?",
         "For a domestic flight we suggest arriving at MSP about 90 minutes before departure, and about two and a half hours for international. Add the drive from your address, roughly 20 minutes from downtown Minneapolis and 10 from Bloomington, and that is your pickup time. Dispatch recommends a window when you book and adjusts it for rush hour or snow."),
        ("Do you handle international arrivals at MSP?",
         "Yes. International flights arrive at Terminal 1 Lindbergh and clear customs on the lower level, and your fare includes 60 minutes of complimentary waiting from the actual landing time. Your chauffeur tracks the flight, waits through customs, and can meet you at the international arrivals exit with a name sign for $15."),
        ("Can I add a child car seat to an airport black car booking?",
         "Yes. Child car seats are $25 each, up to four per vehicle, and they are installed before your chauffeur leaves for the airport. Choose the seat type when you book so the right one is fitted. The Cadillac Escalade is the best choice for a family with two or more seats and luggage."),
        ("What if the airline cancels my flight after I have booked?",
         "Call or text dispatch at (612) 999-5382 and we move the ride to your new flight at no charge. Cancellation is free up to 24 hours before the scheduled pickup, and for airline cancellations inside that window we simply reschedule rather than charge. Dispatch is staffed around the clock, so a midnight rebooking is fine."),
        ("How do I pay for an MSP black car?",
         "Two ways. Pay online by card through Stripe when you book and the receipt arrives by email, or pay your chauffeur at the end of the ride. The flat fare is the same either way, and any extras such as Meet & Greet or a car seat are listed as separate lines before you confirm."),
    ],

    'airport-pickup.html': [
        ("Where does the chauffeur wait for a curbside pickup at Terminal 2 Humphrey?",
         "At the arrivals-level curb directly outside the Terminal 2 baggage claim doors, which are a short walk from the carousels. Your chauffeur texts the door number and a description of the vehicle as you land, then pulls forward when you step outside. Meet & Greet inside the terminal is available at Terminal 2 for $15 as well."),
        ("Can you pick up an elderly parent or a child travelling alone at MSP?",
         "Yes, and for those pickups we recommend Meet & Greet for $15. Your chauffeur waits inside at baggage claim with a name sign, helps with bags, and walks with the passenger to the car. You receive a text when they are collected and another when they are dropped off at the destination."),
        ("What happens if I miss my connection and land on a later flight?",
         "Tell dispatch the new flight number by phone or text and we retime the pickup at no charge. Because we track the flight you enter, a missed connection is one of the few changes we cannot see automatically, so a quick message keeps your chauffeur from staging for the wrong arrival."),
        ("Do you pick up at MSP late at night or very early in the morning?",
         "Yes. Dispatch is staffed 24 hours a day, and red-eye arrivals landing at 1 AM or the first flights in before 6 AM are normal for us. Your chauffeur is staged when the aircraft touches down, and the flat fare you saw at booking is what you pay regardless of the hour."),
        ("How will I know which car and chauffeur to look for?",
         "Your booking confirmation arrives by email and text, and when your flight lands your chauffeur texts their name, the vehicle, its color and the exact door or baggage claim carousel to meet at. Every car is a black Cadillac Escalade, Mercedes-Benz S-Class or Lincoln Continental, so you are never scanning for a stranger's sedan."),
    ],

    'minneapolis-car-service.html': [
        ("Can I book a Minneapolis car service for someone else?",
         "Yes. Enter the passenger's name and mobile number when you book and the confirmation, the reminder and the chauffeur's arrival text go to them, while the receipt comes to you. Parents booking for students, assistants booking for executives and families booking for visiting relatives do this every day, and payment stays with the person who booked."),
        ("Do you provide car service to Minneapolis hospitals and clinics?",
         "Yes. Abbott Northwestern, HCMC, the University of Minnesota Medical Center and the clinics around them are regular destinations. Book point to point each way, or hourly with a three-hour minimum so the same chauffeur waits during the appointment and drives you home. Your chauffeur helps with bags, walkers and the door."),
        ("Do I get a receipt for a Minneapolis car service ride?",
         "Yes. A receipt with the date, route, vehicle and fare is emailed after every ride, whether you paid online through Stripe or paid the chauffeur. Companies that ride often can move to a corporate account with one monthly invoice, saved travelers and a dedicated booking contact."),
        ("How early does the chauffeur arrive for a Minneapolis pickup?",
         "About ten minutes before the booked time. Your chauffeur texts when they are staged outside, waits at the curb or the hotel entrance you named, and never charges for arriving early. If you need a few extra minutes, reply to the text and the car stays put."),
        ("Can you take a ride from Minneapolis to a suburb or another city?",
         "Yes. Every ride is a flat fare from your Minneapolis address to any Twin Cities suburb, MSP, or long-distance destinations such as Rochester and Mayo Clinic in about 90 minutes, St. Cloud in about 75 minutes, Mankato in about 85 minutes and Duluth in about two and a half hours. The full fare appears before you confirm."),
    ],

    'limousine-service-minneapolis.html': [
        ("Should I choose the S-Class or the Escalade for a date night?",
         "For two people the Mercedes-Benz S-Class is the more intimate ride, with a quiet cabin and rear seats built for comfort, from $59 on a point-to-point booking. For four to six friends, or an evening with coats and bags, the Cadillac Escalade seats six from $69. Both carry the same chauffeur standard."),
        ("Can you pick us up after a concert at Target Center or the Armory?",
         "Yes. Your chauffeur agrees a pickup spot with you before the show, usually a side street a block from the venue where the car can stage without the post-show gridlock, and texts when they are in place. Book the return with the outbound and the round trip saves 10 percent."),
        ("Do you offer limo service for prom or homecoming?",
         "Yes. A parent or guardian books the ride, up to six students ride together in the Cadillac Escalade, and the chauffeur follows the itinerary the parent sets, with pickup, photos, dinner, the dance and the ride home. Every stop is agreed at booking, and dispatch can text the parent at each one."),
        ("Can we make several stops on a single-trip limo booking?",
         "Yes. Add stops for $15 each when you book point to point, which works well for collecting friends on the way to dinner. If you expect the car to wait at each stop or the plan is still forming, hourly service with a three-hour minimum usually costs less and keeps the chauffeur with you all evening."),
        ("Is limo service available outside Minneapolis, in Saint Paul or the suburbs?",
         "Yes. We provide the same chauffeured Escalade and S-Class service in Saint Paul, Edina, Wayzata, Eagan, Woodbury and every Twin Cities suburb, plus long evenings that end at a lake home or a suburban hotel. The fare is quoted flat before you confirm and does not surge on event nights."),
    ],

    'hourly-car-service.html': [
        ("When does the hourly clock start?",
         "At the pickup time you booked, not when the chauffeur arrives. Chauffeurs stage about ten minutes early at no charge. The block runs continuously from that start time until you release the car, and it is billed in whole hours with a three-hour minimum, at the rate quoted when you booked."),
        ("Can I book hourly service for a medical appointment?",
         "Yes. Hourly service is the simplest way to have the same chauffeur drop you at the clinic entrance, wait during the appointment and drive you home, whether that is Fairview Southdale in Edina, Abbott Northwestern in Minneapolis or Regions in Saint Paul. Three hours covers most appointments, and the rate is quoted at booking."),
        ("What if I finish before my booked hours are up?",
         "The three-hour minimum still applies, and any hours beyond it that you booked are billed as reserved. You are welcome to use the remaining time for an extra stop, an errand or a detour along the lakes. If you routinely finish early, book the minimum and extend on the day instead."),
        ("Can an hourly booking start with an airport pickup at MSP?",
         "Yes. Set MSP as the starting address, give us the flight number, and the block begins at the scheduled landing time with the flight tracked in the usual way. From there the chauffeur can take you to a hotel, a meeting and dinner without a second booking. Meet & Greet at baggage claim is available for $15."),
        ("Can I split an hourly booking across two days?",
         "No. Each hourly booking is one continuous block with its own three-hour minimum, so an afternoon today and a morning tomorrow are two reservations. For a multi-day visit, tell dispatch the full schedule and we will assign the same chauffeur to every day whenever availability allows."),
    ],

    'private-chauffeur-service.html': [
        ("Can I book a private chauffeur for several consecutive days?",
         "Yes. Each day is booked as its own as-directed block with a three-hour minimum, and dispatch schedules the same chauffeur across all of them whenever availability allows. Give us the itinerary once, including hotel, meetings and airport legs, and the chauffeur arrives each morning already briefed."),
        ("Can your chauffeur drive my own car?",
         "No. Our chauffeurs drive only our own Cadillac Escalade, Mercedes-Benz S-Class and Lincoln Continental, which are maintained, insured and detailed by us before every reservation. That is how we keep the standard consistent. If you need your vehicle moved, dispatch can suggest a separate arrangement."),
        ("What happens if my day runs past the hours I booked?",
         "Tell your chauffeur and the booking extends in whole hours at the rate quoted when you booked, subject to the chauffeur's next commitment. Dispatch can usually confirm the extension within minutes. Booking an extra hour up front is cheaper than a second reservation, so err on the long side for board days."),
        ("Is a private chauffeur a good choice for a medical day in the Twin Cities?",
         "Yes. One chauffeur handles the drop-off at the clinic entrance, waits through the appointment, helps with a walker or bags, and drives on to the pharmacy and home. It suits days at Mayo Clinic in Rochester, the University of Minnesota Medical Center or Abbott Northwestern, and the rate covers all waiting."),
        ("Does the chauffeur take breaks, and do I need to provide meals?",
         "Your chauffeur takes breaks while you are inside a meeting or a restaurant and stays reachable by text the whole day. You are not expected to provide meals or parking, and there are no separate charges for either inside the Twin Cities. The rate quoted at booking is the whole cost of the day."),
    ],

    # ---------------------------------------------------------------- services B

    'point-to-point-transportation.html': [
        ("What if I am running late for my point-to-point pickup?",
         "Text or call your chauffeur, whose number arrives with the confirmation. A few minutes is never an issue, and the flat fare does not change. If the delay stretches to half an hour or more, call dispatch at (612) 999-5382 so we can hold the car or retime the pickup around the chauffeur's next reservation."),
        ("Can I set up the same point-to-point ride every week?",
         "Yes. Dispatch loads a standing reservation, for example every Monday at 6 AM from Edina to Terminal 1, and repeats it until you say otherwise. Each run is confirmed by text, and you can skip or move a date with a call. Corporate accounts can put standing rides on one monthly invoice."),
        ("Can other people ride with me on a point-to-point booking?",
         "Yes, up to the vehicle's capacity at no extra charge: three passengers in the Lincoln Continental or Mercedes-Benz S-Class, six in the Cadillac Escalade. Everyone shares the one flat fare. If your companions board at a different address, add that pickup as a stop for $15."),
        ("Can I change the drop-off address after I have booked?",
         "Yes. Call dispatch or tell your chauffeur, and the fare is recalculated for the new route with no change fee. A shorter trip costs less and a longer one costs more, but you hear the new number before the car turns. Changes to the pickup address work the same way."),
        ("Do you do point-to-point rides across the border into Wisconsin?",
         "Yes. Hudson, River Falls and the St. Croix Valley are regular runs, and the fare is one flat number quoted before you confirm. A ride from MSP to Hudson takes about 35 minutes on I-94. Further destinations in Wisconsin are quoted individually by dispatch."),
    ],

    'group-transportation.html': [
        ("Do you have a vehicle for 10 to 14 passengers?",
         "We own a Mercedes-Benz Sprinter that seats up to 14, and it is temporarily unavailable for online booking. Call dispatch at (612) 999-5382 to ask about it for your date. Otherwise, a group of 10 to 14 rides in two or three vehicles dispatched together, typically an Escalade for six plus one or two sedans."),
        ("How much does group transportation cost?",
         "It is the sum of the flat fares for each vehicle, quoted as one number before you confirm. A group of nine to MSP might use a Cadillac Escalade from $69 and a Lincoln Continental from $49, plus distance. There is no per-passenger charge, and a round trip saves 10 percent on the whole set."),
        ("Can you collect a group arriving on different flights at MSP?",
         "Yes. Each vehicle is tied to a specific flight number and tracked separately, so relatives landing at Terminal 1 at 2 PM and Terminal 2 at 4 PM each meet their own chauffeur and travel to the same address. Meet & Greet with a name sign is $15 per vehicle, and 30 minutes of waiting is included per domestic arrival."),
        ("Can a group travel long distance, to Rochester or Duluth?",
         "Yes. Two or three vehicles travel together to Rochester and Mayo Clinic in about 90 minutes, to Duluth in about two and a half hours or to St. Cloud in about 75 minutes, on one flat quote for the whole group. In winter we recommend the Escalade leads the convoy, and dispatch tracks every car."),
        ("How much luggage or equipment can a group bring?",
         "Plan on six bags in the Cadillac Escalade and three in each sedan. Hockey bags, golf clubs and instrument cases count toward that space, so tell dispatch what you are carrying when you call and we size the fleet so nothing rides on a lap. Skis and sticks fit in the Escalade with the third row folded."),
    ],

    'flight-crew-charter-service.html': [
        ("Can a crew of 10 or more ride in one vehicle?",
         "We own a Mercedes-Benz Sprinter that seats up to 14, and it is temporarily unavailable for online booking, so ask dispatch about it for your rotation. In the meantime a full wide-body crew rides in two or three vehicles dispatched together to the same report time, with one dispatcher coordinating all of them."),
        ("How does the crew know which vehicle is theirs?",
         "The lead crew member receives a text with the chauffeur's name, the vehicle and its position in the hotel driveway before the pickup time. Chauffeurs also carry a sign with the airline or crew code when a hotel has several black cars staged, and the chauffeur confirms the crew count against the manifest before leaving."),
        ("Do you handle crew repositioning to other airports?",
         "Yes. Crews moving between MSP and Rochester International, St. Cloud Regional or Duluth International ride on a flat quote, as do deadheading crew members going to a hotel in another city. Rochester is about 90 minutes from MSP, St. Cloud about 75 and Duluth about two and a half hours."),
        ("What is the plan for crew pickups in a snowstorm?",
         "We stage earlier, switch the run to the Cadillac Escalade, and dispatch watches the roads through the night. Weather margins are added to the pickup time, not to your invoice. Chauffeurs drive the Bloomington and downtown corridors year-round, so a January report time is treated as routine."),
        ("Is there a minimum number of crew runs per month?",
         "No. A single one-off crew pickup is welcome and is booked and invoiced the same way as a standing rotation. Accounts are set up the same day by phone or email, with each run itemized by date, flight, hotel and vehicle on one monthly statement."),
    ],

    'chauffeur-service-minneapolis.html': [
        ("How will my chauffeur contact me on the day?",
         "By text, about ten minutes before pickup, with their name, the vehicle and where the car is staged. Their number comes with your confirmation so you can reply directly, and dispatch at (612) 999-5382 is available around the clock as a second line. Airport pickups add a text the moment your flight lands."),
        ("Can the chauffeur wait for me during a point-to-point ride?",
         "Short waits are fine, such as dropping a package or collecting a colleague at a stop added for $15. If you want the chauffeur to wait through a dinner or a meeting, hourly service with a three-hour minimum is the right structure and keeps the same car outside until you are ready."),
        ("Can your chauffeurs assist passengers with limited mobility?",
         "Yes. Chauffeurs help passengers in and out of the vehicle, carry a folding wheelchair or walker in the trunk, and walk with you to the entrance. Our vehicles are standard Cadillac Escalade, Mercedes-Benz S-Class and Lincoln Continental models without a lift, so tell dispatch about any needs when you book."),
        ("Do you provide chauffeur service for an executive visiting Minneapolis for the day?",
         "Yes. A typical itinerary is Meet & Greet at MSP baggage claim, a hotel drop, meetings downtown and a return flight, handled as an hourly as-directed block or a set of point-to-point rides, whichever costs less. Corporate accounts add one monthly invoice and a dedicated booking contact."),
        ("Will I have the same chauffeur on the return trip?",
         "Whenever the schedule allows, yes. Round trips booked together save 10 percent and are assigned to the same chauffeur by default, so your preferences and luggage arrangements carry over. If a shift change makes that impossible, dispatch briefs the second chauffeur on your booking notes."),
    ],

    'mall-of-america-car-service.html': [
        ("Where does the car pick up at Mall of America?",
         "At whichever entrance is closest to where you finish: the North, East, South or West entrances, or the hotel lobbies of the JW Marriott and Radisson Blu attached to the mall. Text your chauffeur when you are ready and they name the door and pull up. Point-to-point pickups are set at booking; hourly clients choose freely."),
        ("How much is a car from MSP to Mall of America?",
         "Fares start at $49 in the Lincoln Continental, $59 in the Mercedes-Benz S-Class and $69 in the Cadillac Escalade, plus distance, and because the trip is about three miles most MOA fares stay close to those starting rates. The exact flat fare appears on the booking form before you confirm."),
        ("Can you take us from Mall of America to the Minnesota Zoo or Valleyfair?",
         "Yes. The Minnesota Zoo in Apple Valley is about 15 minutes from the mall, and Valleyfair in Shakopee is about 25 minutes. Both are quoted as flat point-to-point fares, and a round trip booked together saves 10 percent. Car seats are $25 each for families with young children."),
        ("Can you move a group larger than six between MOA and MSP?",
         "Yes. We dispatch two or three vehicles together on one booking, for example a Cadillac Escalade for six plus a sedan for three, timed to the same terminal and flight. One dispatcher coordinates them and you receive a single confirmation and invoice. Groups above six are arranged by phone."),
        ("Can I get a ride from a Mall of America hotel to a Vikings or Twins game?",
         "Yes. U.S. Bank Stadium and Target Field are about 20 minutes from the MOA hotels on Highway 77 and I-35W. Your chauffeur drops you near the gate and meets you at an agreed spot afterward, and the flat fare does not surge on game days. Book both legs together and save 10 percent."),
    ],

    'contact.html': [
        ("What information do I need to book a ride?",
         "Pickup address, destination, date, time, passenger count and a mobile number for texts. For airport rides add the airline and flight number so we can track it and pick the terminal. Extras such as Meet & Greet for $15, car seats for $25 each and extra stops for $15 each can be added at the same time."),
        ("Can I get a quote without booking?",
         "Yes. Enter the trip on the booking form and the flat fare for each vehicle appears before you confirm anything, with no account required. For hourly service, groups larger than six or long-distance trips, call (612) 999-5382 and dispatch quotes it on the phone in about a minute."),
        ("What payment methods do you accept?",
         "Card payment online through Stripe when you book, or payment to your chauffeur at the end of the ride. Corporate clients can be invoiced monthly instead. The flat fare is identical whichever way you pay, and a receipt is emailed after every ride."),
        ("Do you have anything larger than a six-passenger SUV?",
         "Yes. We own a Mercedes-Benz Sprinter that seats up to 14, and it is temporarily unavailable for online booking, so call dispatch to ask about it. For most groups above six we send two or three vehicles together, such as a Cadillac Escalade plus a sedan, on one confirmation and one invoice."),
        ("Where is Total Town Car Service based and how far do you travel?",
         "We are based in Minneapolis and have operated since 1991, with more than 10,000 rides completed. We serve Minneapolis, Saint Paul, every Twin Cities suburb and MSP Airport, and drive long distance to Rochester and Mayo Clinic, St. Cloud, Mankato, Duluth and Hudson, Wisconsin, on flat fares quoted before you confirm."),
    ],

    # ------------------------------------------------------------------ cities A

    'car-service-minneapolis.html': [
        ("Do you provide car service to Target Field, U.S. Bank Stadium and Target Center?",
         "Yes. Your chauffeur drops you at the gate closest to your section and meets you at an agreed spot a block away afterward, so you skip the ramps. The flat fare does not surge on game nights, and booking the ride to and from the game together saves 10 percent."),
        ("Can you pick up a University of Minnesota student for a flight home?",
         "Yes. We pick up at the dorms, Dinkytown, Stadium Village and the St. Paul campus and reach MSP in about 20 minutes. Parents usually book and pay, enter the student's mobile number for the texts, and the chauffeur helps with the bags. For move-in weekends the Escalade carries six bags."),
        ("What do extra stops and car seats cost on a Minneapolis ride?",
         "Extra stops are $15 each, useful for collecting a colleague in the North Loop on the way to MSP. Child car seats are $25 each, up to four, installed before pickup. Both are added on the booking form and shown as separate lines before you confirm the flat fare."),
        ("Do you serve Abbott Northwestern, HCMC and the University of Minnesota Medical Center?",
         "Yes. Patient and visitor rides to Abbott Northwestern, HCMC, the University of Minnesota Medical Center and Children's Minnesota are daily work for us. Book point to point each way, or hourly with a three-hour minimum so the same chauffeur waits through the appointment and drives you home."),
        ("Can you drive me from Minneapolis to Rochester or Duluth?",
         "Yes. Minneapolis to Rochester and Mayo Clinic is about 90 minutes on Highway 52, and Duluth is about two and a half hours on I-35. Both are quoted as one flat fare before you confirm, the round trip saves 10 percent, and in winter we recommend the Cadillac Escalade."),
    ],

    'car-service-saint-paul.html': [
        ("Is there a discount for booking a Saint Paul airport ride both ways?",
         "Yes. Book the departure and the return together and the total drops by 10 percent. The return leg is tracked against your inbound flight, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur is assigned whenever the schedule allows."),
        ("Can you pick us up after a Wild game or an Ordway show?",
         "Yes. Your chauffeur drops you at the Xcel Energy Center or Ordway door on Kellogg Boulevard and meets you after at an agreed spot on West Seventh or Washington Street, away from the post-event crush. The flat fare does not surge on game nights, and a round trip saves 10 percent."),
        ("Do you serve Regions Hospital, United Hospital and Children's Minnesota in Saint Paul?",
         "Yes. Patient, visitor and physician rides to Regions, United, Children's Minnesota and Gillette are routine. Book point to point each way or hourly with a three-hour minimum so the same chauffeur waits during the appointment. Chauffeurs help with walkers and bags and drop you at the entrance you name."),
        ("Can you pick up students at Macalester, Saint Thomas, Hamline or Concordia?",
         "Yes. Campus pickups for flights, move-in and family visits are regular runs, and all four campuses reach MSP in about 15 to 20 minutes. Parents can book and pay from out of town, enter the student's mobile number for the texts, and add a Meet & Greet at baggage claim for $15."),
        ("Can I add a child car seat or an extra stop on a Saint Paul ride?",
         "Yes. Child car seats are $25 each, up to four, and are installed before pickup. Extra stops are $15 each, useful for collecting grandparents on Summit Avenue on the way to the airport. Both appear as separate lines on the booking form before you confirm the flat fare."),
    ],

    'car-service-bloomington.html': [
        ("Do you provide executive rides to Normandale Lake and the HealthPartners campus?",
         "Yes. The Normandale Lake office park, the HealthPartners headquarters and the offices along France Avenue and West 78th Street are core corporate routes for us, about 12 minutes from MSP. Companies can open an account with one monthly invoice, saved travelers and a dedicated booking contact."),
        ("Can you take me from a Bloomington hotel to downtown Minneapolis for dinner?",
         "Yes. Downtown Minneapolis is about 20 minutes from the I-494 hotels on I-35W or Highway 77, quoted as one flat fare. Book the ride back at the same time and the pair saves 10 percent, with your chauffeur waiting at an agreed spot when dinner ends."),
        ("Is a round trip from Bloomington to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your inbound flight, with 30 minutes of complimentary waiting after a domestic landing, so a late arrival still meets a waiting chauffeur at the terminal."),
        ("Can you drive us from Bloomington to the Minnesota Zoo or Valleyfair?",
         "Yes. The Minnesota Zoo in Apple Valley is about 15 minutes from the Mall of America hotels, and Valleyfair in Shakopee is about 25 minutes. Both are flat point-to-point fares, and the Cadillac Escalade seats six with strollers and bags for a family day."),
        ("Are child car seats available for a family leaving the JW Marriott or Radisson Blu?",
         "Yes. Car seats are $25 each, up to four, installed before your chauffeur arrives at the hotel. Choose the seat type when you book. The Cadillac Escalade is the right vehicle for a family with car seats and airport luggage, with room for six passengers and six bags."),
    ],

    'car-service-edina.html': [
        ("Do you offer a discount for a round trip from Edina to MSP?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. Your return flight is tracked, 30 minutes of complimentary waiting is included after a domestic landing, and the same chauffeur is assigned whenever the schedule allows."),
        ("Can I add car seats for a family ride from Edina?",
         "Yes. Child car seats are $25 each, up to four per vehicle, and they are installed before the chauffeur reaches your driveway. The Cadillac Escalade seats six with six bags, which suits an Edina family heading to MSP with luggage and two car seats."),
        ("Can you meet visiting relatives at MSP and bring them to Edina?",
         "Yes. Give us their flight number and we track it, wait 30 minutes at no charge after a domestic landing, and can add Meet & Greet for $15 so a chauffeur is at baggage claim with a name sign. The drive to Edina takes about 20 minutes and the flat fare is set when you book."),
        ("Can an Edina company set up a corporate account?",
         "Yes. Offices along France Avenue, at Centennial Lakes and around Southdale use us for executive and visitor transportation on accounts with one monthly invoice, saved travelers and receipts for every ride. Call dispatch or use the corporate transportation page to get started, usually the same day."),
        ("Do you drive to events at Interlachen Country Club and Edina Country Club?",
         "Yes. Club dinners, galas and golf outings at Interlachen and Edina Country Club are regular evening runs, with a chauffeur staged when the event ends. Book point to point each way, or hourly with a three-hour minimum if the evening includes a stop at 50th & France first."),
    ],

    'car-service-minnetonka.html': [
        ("Is there a discount for booking a Minnetonka airport ride both ways?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your flight, with 30 minutes of complimentary waiting after a domestic landing, so a delayed arrival still meets a waiting chauffeur for the 25-minute ride home."),
        ("Can you drive me from Minnetonka to Rochester for a Mayo Clinic appointment?",
         "Yes. Minnetonka to Mayo Clinic is about two hours on I-494 and Highway 52, quoted as one flat fare before you confirm. The round trip saves 10 percent, returns are timed around your last appointment, and the Cadillac Escalade is the right choice for Highway 52 in winter."),
        ("Which vehicle is best for a Minnetonka airport run in winter?",
         "The Cadillac Escalade. It handles snow on I-494 and Highway 62 with confidence, seats six and carries six bags. The Mercedes-Benz S-Class and Lincoln Continental are excellent on cleared roads and suit one to three passengers. Whichever you pick, chauffeurs add time for winter conditions."),
        ("Can I book hourly service for a day around Lake Minnetonka?",
         "Yes. Hourly service with a three-hour minimum keeps a chauffeur with your group for lunch in Excelsior, a stop in Wayzata and dinner on the water, quoted at booking. The Escalade seats six for visiting family or a corporate group and waits at each stop."),
        ("Do you also serve Hopkins, Deephaven, Shorewood and Excelsior?",
         "Yes. Every address around Minnetonka, including Hopkins, Deephaven, Shorewood, Excelsior, Tonka Bay and Orono, is a normal ride for us, quoted flat before you confirm. Airport runs from those towns take about 25 to 35 minutes, and dispatch is staffed 24 hours a day."),
    ],

    'car-service-eden-prairie.html': [
        ("Is there a discount for booking an Eden Prairie airport ride both ways?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. Your inbound flight is tracked, 30 minutes of complimentary waiting is included after a domestic landing, and the same chauffeur drives both legs whenever the schedule allows."),
        ("Do you pick up at Eden Prairie Center and the nearby hotels?",
         "Yes. Eden Prairie Center, the restaurants on Prairie Center Drive and the hotels clustered near Flying Cloud Drive and I-494 are regular pickups, about 20 minutes from MSP. Tell us the hotel or restaurant entrance and your chauffeur will be at the door with a text when they arrive."),
        ("Can you take a team of eight from an Eden Prairie office to MSP?",
         "Yes. For more than six we dispatch two vehicles together, usually a Cadillac Escalade for six and a sedan for the rest, timed to the same terminal on one confirmation and one invoice. Groups above six are arranged by phone so dispatch can plan the luggage and the timing."),
        ("Can you drive us to the Chanhassen Dinner Theatres or a game downtown?",
         "Yes. Chanhassen Dinner Theatres is about 10 minutes from Eden Prairie, and U.S. Bank Stadium and Target Field are about 25 minutes. Your chauffeur drops you at the door, stages nearby when the show or game ends, and the flat fare does not surge on event nights."),
        ("Can I add a child car seat for a family flying out of Eden Prairie?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives. Families around Staring Lake and Bearpath usually choose the Cadillac Escalade, which seats six with six bags, so car seats, strollers and luggage all fit for the 20-minute run to MSP."),
    ],

    'car-service-plymouth.html': [
        ("Is a round trip from Plymouth to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return leg is tracked against your flight, with 30 minutes of complimentary waiting after a domestic landing, so a late arrival still meets a waiting chauffeur for the 30-minute drive home."),
        ("Which route do you take from Plymouth to MSP in rush hour?",
         "Your chauffeur chooses on the day between I-494 south, Highway 55 to I-35W and Highway 62, or Highway 169 to I-494, depending on live traffic. The flat fare does not change with the route or the time it takes, and pickups are scheduled with a cushion for the morning commute."),
        ("Can you move a group larger than six from Plymouth?",
         "Yes. For seven or more we dispatch two or three vehicles together, typically a Cadillac Escalade plus a sedan, timed to the same terminal or venue on one booking and one invoice. Groups above six are arranged by phone so dispatch can plan luggage, car seats and pickup order."),
        ("Can you drive us to Wayzata or downtown Minneapolis for dinner and bring us back?",
         "Yes. Wayzata is about 10 minutes from Plymouth and downtown Minneapolis about 25. Book point to point each way and the pair saves 10 percent, or book hourly with a three-hour minimum if the chauffeur should wait through dinner and continue to a second stop."),
        ("Can I book a ride from Plymouth to St. Cloud, Duluth or Rochester?",
         "Yes. Plymouth to St. Cloud is about an hour on I-94, Duluth about two and a half hours and Rochester about 100 minutes, each quoted as one flat fare before you confirm. The round trip saves 10 percent, and the Cadillac Escalade is our winter recommendation for all three."),
    ],

    'car-service-maple-grove.html': [
        ("Is a round trip from Maple Grove to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your inbound flight, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur is assigned whenever the schedule allows."),
        ("Do you provide corporate rides for the Boston Scientific campus?",
         "Yes. Executive and visitor transportation for the Boston Scientific campus and the offices near I-94 and Highway 610 is a regular part of our week, about 30 minutes to MSP. Companies can open an account with one monthly invoice, saved travelers and a dedicated booking contact."),
        ("Can you drive from Maple Grove to St. Cloud or Duluth?",
         "Yes. Maple Grove to St. Cloud is about 50 minutes on I-94, and Duluth is about two and a half hours on I-94 and I-35, each quoted as one flat fare before you confirm. The round trip saves 10 percent, and in winter we recommend the Cadillac Escalade."),
        ("Do you also serve Osseo, Champlin, Brooklyn Park and Rogers?",
         "Yes. Every address in the northwest metro, including Osseo, Champlin, Brooklyn Park, Rogers, Dayton and Corcoran, is a normal ride for us. Airport runs from those cities take about 30 to 40 minutes, the fare is quoted flat before you confirm, and dispatch is staffed 24 hours a day."),
        ("Can I add a child car seat for a ride from Maple Grove to MSP?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives in your driveway. Families around Weaver Lake and Rice Lake usually choose the Cadillac Escalade, which seats six with six bags, so car seats and luggage fit for the 30-minute run to MSP."),
    ],

    'car-service-wayzata.html': [
        ("Is a round trip from Wayzata to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your flight, with 30 minutes of complimentary waiting after a domestic landing, so a late arrival still meets a waiting chauffeur for the 30-minute drive back to the lake."),
        ("Do you pick up at the Cargill headquarters campus?",
         "Yes. Executive and visitor rides between the Cargill campus in Wayzata and MSP, downtown Minneapolis and the hotels along Wayzata Boulevard are a regular part of our week. Companies can open a corporate account with one monthly invoice, saved travelers and a dedicated booking contact."),
        ("Can you meet weekend guests at MSP and bring them to a Lake Minnetonka home?",
         "Yes. Give us their flight number and we track it, wait 30 minutes at no charge after a domestic landing, and for $15 a chauffeur meets them at baggage claim with a name sign. The drive to Wayzata takes about 30 minutes and the flat fare is set when you book."),
        ("Do you also serve Orono, Long Lake, Deephaven and Minnetonka Beach?",
         "Yes. Every address around the lake, including Orono, Long Lake, Deephaven, Minnetonka Beach, Woodland and Spring Park, is a normal ride for us, quoted flat before you confirm. Airport runs from the north shore take about 30 to 40 minutes, and dispatch is staffed 24 hours a day."),
        ("Which vehicle should I choose for a Wayzata airport run in winter?",
         "The Cadillac Escalade. It handles snow on I-394 and I-494 with confidence and seats six with six bags. The Mercedes-Benz S-Class and Lincoln Continental suit one to three passengers on cleared roads. Whichever you choose, chauffeurs add extra time to winter pickups."),
    ],

    'car-service-woodbury.html': [
        ("Is a round trip from Woodbury to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your inbound flight, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur drives both legs whenever the schedule allows."),
        ("Can you take me to Woodwinds Hospital and wait during an appointment?",
         "Yes. Book point to point each way, or hourly with a three-hour minimum so the same chauffeur waits at Woodwinds Hospital or the nearby clinics and drives you home. Chauffeurs help with walkers and bags and drop you at the entrance you name. The price is quoted before you confirm."),
        ("Can I book a car from Woodbury to Rochester for Mayo Clinic?",
         "Yes. Woodbury to Mayo Clinic is about 90 minutes on I-494 and Highway 52, quoted as one flat fare before you confirm. The round trip saves 10 percent, returns are timed around your last appointment, and the Cadillac Escalade is our recommendation for Highway 52 in winter."),
        ("Can a Woodbury company set up a corporate account?",
         "Yes. Offices along Hudson Road, the I-94 corridor and CityPlace use us for executive and visitor transportation on accounts with one monthly invoice, saved travelers and receipts for every ride. Call dispatch or use the corporate transportation page to get started, usually the same day."),
        ("Can you take us to a Wild game at the Xcel Energy Center and pick us up after?",
         "Yes. Downtown Saint Paul is about 15 minutes from Woodbury on I-94. Your chauffeur drops you at the Xcel Energy Center door and meets you afterward at an agreed spot on West Seventh, away from the crowd. The flat fare does not surge on game nights, and a round trip saves 10 percent."),
    ],

    'car-service-eagan.html': [
        ("Is a round trip from Eagan to MSP discounted?",
         "Yes. Booking the departure and the return together saves 10 percent on the pair. The return is tracked against your flight, with 30 minutes of complimentary waiting after a domestic landing, and because Eagan is only about 12 minutes away, a late arrival still gets home quickly."),
        ("Can you take a group from Viking Lakes to a Vikings game at U.S. Bank Stadium?",
         "Yes. U.S. Bank Stadium is about 20 minutes from the Omni Viking Lakes Hotel. The Cadillac Escalade seats six, and larger groups get two or three vehicles dispatched together on one booking. Your chauffeur drops you near the gate and meets you at an agreed spot afterward, with no surge on game days."),
        ("Do you also serve Inver Grove Heights, Mendota Heights and Rosemount?",
         "Yes. Every address in the south metro around Eagan, including Inver Grove Heights, Mendota Heights, Rosemount and Sunfish Lake, is a normal ride for us, quoted flat before you confirm. Airport runs from those cities take about 12 to 25 minutes, and dispatch is staffed 24 hours a day."),
        ("Can I book a car from Eagan to Rochester?",
         "Yes. Eagan sits at the top of Highway 52, so Mayo Clinic and downtown Rochester are about 80 minutes away, quoted as one flat fare before you confirm. The round trip saves 10 percent, returns are timed to your last appointment, and the Cadillac Escalade is our winter recommendation."),
        ("Can you meet visiting family at MSP and bring them to Eagan with car seats?",
         "Yes. We track the flight, wait 30 minutes at no charge after a domestic landing, and can add Meet & Greet at baggage claim for $15. Child car seats are $25 each, up to four, installed in advance. The ride to Eagan takes about 12 minutes on Highway 55 or I-494."),
    ],

    # ------------------------------------------------------------------ cities B

    'car-service-burnsville.html': [
        ("Can you take me to Fairview Ridges Hospital and wait for my appointment?",
         "Yes. Book point to point each way, or hourly with a three-hour minimum so the same chauffeur waits at Fairview Ridges Hospital or the clinics along Nicollet Avenue and drives you home. Chauffeurs help with walkers and bags and drop you at the entrance you name. The price is quoted before you confirm."),
        ("Do you provide child car seats for a Burnsville family flying out of MSP?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur reaches your driveway. Most Burnsville families choose the Cadillac Escalade, which seats six with six bags, so car seats, strollers and luggage all fit for the 20-minute run up Highway 77 to the terminal."),
        ("Can you handle a group larger than six from Burnsville?",
         "Yes. For seven or more we dispatch two or three vehicles together, typically a Cadillac Escalade plus a sedan, timed to the same terminal or venue on one booking and one invoice. Groups above six are arranged by phone so dispatch can plan luggage, ski gear and pickup order."),
        ("Do you also serve Savage, Prior Lake and Shakopee?",
         "Yes. Every address in the southwest metro, including Savage, Prior Lake, Shakopee and Credit River, is a normal ride for us, quoted flat before you confirm. Airport runs from those cities take about 25 to 35 minutes, and dispatch is staffed 24 hours a day for early flights."),
        ("Can I book a ride from Burnsville to Mankato or Rochester?",
         "Yes. Burnsville to Mankato is about 65 minutes on I-35 and Highway 169, and Rochester is about 75 minutes on I-35 and Highway 52, each quoted as one flat fare before you confirm. The round trip saves 10 percent, and the Cadillac Escalade is our winter recommendation."),
    ],

    'car-service-lakeville.html': [
        ("Do you provide prom or homecoming rides for Lakeville North and Lakeville South?",
         "Yes. A parent books, up to six students ride together in the Cadillac Escalade, and the chauffeur follows the itinerary the parent set, from pickup and photos to dinner, the dance and home. Every stop is agreed at booking, and the flat fare is shown before you confirm."),
        ("Are child car seats available for a Lakeville family?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives. Families around Lake Marion and Antlers Park usually choose the Cadillac Escalade, which seats six with six bags, so car seats and airport luggage fit comfortably for the 30-minute run to MSP."),
        ("Can I book a ride from Lakeville to the Mall of America or the Minnesota Zoo?",
         "Yes. Mall of America is about 25 minutes from Lakeville on I-35 and I-494, and the Minnesota Zoo in Apple Valley is about 15 minutes. Both are flat point-to-point fares, a round trip booked together saves 10 percent, and hourly service is available if you want the car to wait."),
        ("Do you also serve Farmington, Elko New Market and Credit River?",
         "Yes. Every address south of the metro, including Farmington, Elko New Market, Credit River and Northfield, is a normal ride for us, quoted flat before you confirm. Airport runs from those towns take about 35 to 50 minutes, and dispatch is staffed 24 hours a day for early flights."),
        ("Which vehicle do you recommend for a Lakeville family with a lot of luggage?",
         "The Cadillac Escalade, which seats six passengers with six bags and handles I-35 in winter. For one to three travelers with three bags, the Mercedes-Benz S-Class from $59 or the Lincoln Continental from $49 is the better value. Fares are quoted flat before you confirm."),
    ],

    'car-service-apple-valley.html': [
        ("Do you provide child car seats for zoo trips and airport rides?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives. The Cadillac Escalade seats six with strollers and bags, which suits a Minnesota Zoo day with grandparents or a family departure from MSP, about 25 minutes up Cedar Avenue."),
        ("Can you drive from Apple Valley to Rochester or Mankato?",
         "Yes. Apple Valley to Rochester and Mayo Clinic is about 75 minutes on Highway 52, and Mankato is about 70 minutes on Highway 169, each quoted as one flat fare before you confirm. The round trip saves 10 percent, and the Cadillac Escalade is our winter recommendation."),
        ("Can I get a ride from Apple Valley to the Mall of America?",
         "Yes. Mall of America is about 15 minutes from Apple Valley on Cedar Avenue and Highway 77, quoted as a flat fare from $49 in the sedan. Book both directions together and save 10 percent, or book hourly with a three-hour minimum if you want the chauffeur to wait while you shop."),
        ("Do you also serve Rosemount and Farmington?",
         "Yes. Every address in Dakota County around Apple Valley, including Rosemount, Farmington, Lakeville and Eagan, is a normal ride for us, quoted flat before you confirm. Airport runs from Rosemount and Farmington take about 25 to 35 minutes, and dispatch is staffed 24 hours a day."),
        ("Can you handle a group of eight for a Minnesota Zoo day?",
         "Yes. For more than six we dispatch two vehicles together, usually a Cadillac Escalade for six and a sedan for the rest, timed to arrive at the zoo entrance at the same time on one booking and one invoice. Groups above six are arranged by phone so dispatch can plan car seats and pickup order."),
    ],

    'car-service-roseville.html': [
        ("Can I book a car from a Roseville hotel to downtown Minneapolis or Saint Paul?",
         "Yes. Both downtowns are about 10 to 15 minutes from the hotels near Rosedale Center, quoted as a flat fare from $49 in the sedan. Your chauffeur meets you at the hotel entrance, and booking the ride back at the same time saves 10 percent on the pair."),
        ("Do you also serve Shoreview, Arden Hills, Falcon Heights and Little Canada?",
         "Yes. Every address in the north metro around Roseville, including Shoreview, Arden Hills, Falcon Heights, Little Canada and Lauderdale, is a normal ride for us, quoted flat before you confirm. Airport runs from those cities take about 25 to 35 minutes, and dispatch is staffed 24 hours a day."),
        ("Can a Roseville company set up a corporate account?",
         "Yes. Offices along Highway 36, County Road C and the Rosedale area use us for executive and visitor transportation on accounts with one monthly invoice, saved travelers and receipts for every ride. Call dispatch or use the corporate transportation page to get started, usually the same day."),
        ("Are child car seats available for a Roseville family?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives. The Cadillac Escalade seats six with six bags, so car seats, luggage and a stroller all fit for the 25-minute run to MSP, and it handles Highway 36 and I-35W in winter."),
        ("Can you drive us to a Gophers game or the University of Minnesota from Roseville?",
         "Yes. Huntington Bank Stadium, Williams Arena and the University of Minnesota campus are about 10 minutes from Roseville. Your chauffeur drops you at the gate, meets you at an agreed spot afterward, and the flat fare does not surge on game days. A round trip booked together saves 10 percent."),
    ],

    'car-service-blaine.html': [
        ("Do you have a vehicle for a full team of 12 to 14?",
         "We own a Mercedes-Benz Sprinter that seats up to 14, and it is temporarily unavailable for online booking, so call dispatch at (612) 999-5382 to ask about it for your tournament dates. Otherwise a team of 12 to 14 rides in three vehicles dispatched together, usually two Escalades and a sedan, on one booking."),
        ("Do you also serve Ham Lake, Lino Lakes, Coon Rapids and Andover?",
         "Yes. Every address in the north metro around Blaine, including Ham Lake, Lino Lakes, Coon Rapids, Andover, Circle Pines and Spring Lake Park, is a normal ride for us, quoted flat before you confirm. Airport runs from those cities take about 35 to 45 minutes, and dispatch is staffed 24 hours a day."),
        ("Will hockey bags and sticks fit in the vehicle?",
         "Yes. The Cadillac Escalade carries six bags in the cargo area, and with the third row folded it takes hockey bags, sticks and a goalie bag for a smaller group. The sedans carry three bags each. Tell dispatch how much gear is coming and we size the vehicles for the National Sports Center run."),
        ("Can I book a ride from Blaine to Duluth or St. Cloud?",
         "Yes. Blaine to Duluth is about two hours and 15 minutes on I-35, and St. Cloud is about an hour on Highway 10 or I-94, each quoted as one flat fare before you confirm. The round trip saves 10 percent, and the Cadillac Escalade is our winter recommendation for both."),
        ("Are child car seats available for a Blaine family?",
         "Yes. Child car seats are $25 each, up to four, installed before the chauffeur arrives. Families in The Lakes and around Northtown usually choose the Cadillac Escalade, which seats six with six bags, so car seats and airport luggage fit for the 35-minute run to MSP."),
    ],

    'car-service-stillwater.html': [
        ("Can you bring wedding guests from MSP to a Stillwater venue?",
         "Yes. We collect guests at MSP baggage claim with a Meet & Greet name sign for $15, track each flight, and drive them about 45 minutes to the Lora, the Water Street Inn or a venue on the river. Groups larger than six ride in two or three vehicles dispatched together on one booking."),
        ("Do you serve Hudson, Wisconsin and the other St. Croix Valley towns?",
         "Yes. Hudson, Bayport, Oak Park Heights, Lake Elmo, Marine on St. Croix and the Wisconsin side of the valley are all regular rides, quoted flat before you confirm. Hudson to MSP takes about 35 minutes on I-94, and dispatch is staffed 24 hours a day for early flights."),
        ("Can you take us from Stillwater to a Wild game or a show at the Ordway?",
         "Yes. Downtown Saint Paul is about 30 minutes from Stillwater on Highway 36 and I-35E. Your chauffeur drops you at the Xcel Energy Center or Ordway door and meets you afterward at an agreed spot, and the flat fare does not surge on event nights. A round trip saves 10 percent."),
        ("Which vehicle is best for a Stillwater airport run in winter?",
         "The Cadillac Escalade. It handles Highway 36 and I-694 in snow with confidence and seats six with six bags. For one to three passengers on cleared roads, the Mercedes-Benz S-Class from $59 or the Lincoln Continental from $49 is the better value. Chauffeurs add time to winter pickups."),
        ("Are child car seats available for a family visiting Stillwater?",
         "Yes. Child car seats are $25 each, up to four, installed before the pickup at MSP or your Stillwater address. The Cadillac Escalade seats six with six bags, so a family with car seats, luggage and a stroller fits comfortably for the 45-minute ride to the river."),
    ],

    'car-service-rochester.html': [
        ("Do you pick up at Rochester International Airport?",
         "Yes. We meet regional flights at Rochester International Airport, track the flight, and drive to Mayo Clinic, a downtown hotel or any Rochester address in about 15 minutes, or on to the Twin Cities in about 90 minutes. Meet & Greet with a name sign is $15 and 30 minutes of waiting is included."),
        ("Can I book a round trip from MSP to Mayo Clinic and back?",
         "Yes. Booking both directions together saves 10 percent on the total. The outbound is tracked against your inbound flight at MSP, and the return is scheduled for the end of your last appointment. If the appointment runs long, call dispatch and we retime the pickup at no charge."),
        ("Can the chauffeur help a patient using a wheelchair or walker?",
         "Yes. Chauffeurs help passengers in and out of the vehicle, carry a folding wheelchair or walker in the trunk, and walk with you to the Gonda Building or Saint Marys entrance. Our vehicles do not have a lift, so tell dispatch about any mobility needs when you book so we can assign the right car."),
        ("What if my Mayo Clinic appointment has no fixed end time?",
         "Book the return for your best estimate and call or text dispatch when you know more. We retime the pickup at no charge, and the chauffeur is staged near the clinic when you are ready. Because the fare is flat, waiting for a text costs you nothing on a Rochester point-to-point ride."),
        ("How much notice do you need for a Rochester trip?",
         "Online bookings need at least two hours, and a day ahead is ideal for a long-distance run so dispatch can assign a chauffeur who drives Highway 52 regularly. Same-day Rochester rides are often possible by phone at (612) 999-5382, and cancellation is free up to 24 hours before pickup."),
    ],

    'car-service-duluth.html': [
        ("Can you move a student into UMD or St. Scholastica with everything they own?",
         "Yes. The Cadillac Escalade carries six passengers with six bags, and with the third row folded it takes bins, a mini fridge and bedding for one student. For a full dorm load or two students we send two vehicles together on one booking. Chauffeurs know the UMD and St. Scholastica dorm entrances."),
        ("Is a round trip between Duluth and MSP discounted?",
         "Yes. Booking both directions together saves 10 percent on the total. The return is tracked against your inbound flight at MSP, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur drives both legs whenever the schedule allows."),
        ("Can you continue past Duluth to Lutsen or Grand Marais on the North Shore?",
         "Yes. North Shore rides to Two Harbors, Lutsen and Grand Marais are quoted as one flat fare before you confirm. Grand Marais is about four and a half hours from MSP on I-35 and Highway 61, and the Cadillac Escalade is our recommendation for the shore road in any season."),
        ("Do you also serve Superior, Wisconsin, Cloquet and Hermantown?",
         "Yes. Superior across the bridge, Cloquet, Hermantown, Proctor and Esko are all normal rides for us, quoted flat before you confirm. Superior to MSP takes about two hours and 40 minutes on I-35, and dispatch is staffed 24 hours a day for early flights."),
        ("Do you pick up at Essentia and St. Luke's for patients travelling to the Twin Cities?",
         "Yes. Patient rides from the Essentia and St. Luke's campuses on the Duluth hillside to specialists in Minneapolis, Saint Paul or Rochester are quoted as one flat fare, with the chauffeur helping with a walker or bags at both ends. Rochester from Duluth is about four hours, quoted the same way."),
    ],

    'car-service-st-cloud.html': [
        ("Can you handle move-in for a St. Cloud State student?",
         "Yes. The Cadillac Escalade carries six passengers with six bags, and with the third row folded it takes bins, bedding and a mini fridge for one student. For a full dorm load we send two vehicles together on one booking. Chauffeurs know the St. Cloud State, Saint John's and Saint Benedict entrances."),
        ("Is a round trip between St. Cloud and MSP discounted?",
         "Yes. Booking both directions together saves 10 percent on the total. The return is tracked against your inbound flight at MSP, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur drives both legs whenever the schedule allows."),
        ("Can you drive from St. Cloud to Rochester for Mayo Clinic?",
         "Yes. St. Cloud to Mayo Clinic is about two and a half hours on I-94, I-494 and Highway 52, quoted as one flat fare before you confirm. Returns are timed around your last appointment, the round trip saves 10 percent, and the Cadillac Escalade is our winter recommendation."),
        ("Can you drop me at Terminal 2 for a Sun Country flight from St. Cloud?",
         "Yes. Give us the airline and flight number and your chauffeur takes you to the correct terminal, Terminal 2 Humphrey for Sun Country and the low-cost carriers or Terminal 1 Lindbergh for most others. Departures leave St. Cloud with a margin for I-94 traffic, check-in and security."),
        ("Can you meet a St. Cloud-bound guest at MSP with a name sign?",
         "Yes. Meet & Greet is $15. The chauffeur waits at baggage claim with a name sign, helps with luggage and walks with your guest to the car for the 75-minute ride to St. Cloud. We track the flight, and 30 minutes of waiting after a domestic landing is included at no charge."),
    ],

    'car-service-mankato.html': [
        ("Can you carry a student's belongings for Minnesota State move-in?",
         "Yes. The Cadillac Escalade carries six passengers with six bags, and with the third row folded it takes bins, bedding and a mini fridge for one student. For a full dorm load we send two vehicles together on one booking. Chauffeurs know the Minnesota State and Bethany Lutheran dorm entrances."),
        ("Is a round trip between Mankato and MSP discounted?",
         "Yes. Booking both directions together saves 10 percent on the total. The return is tracked against your inbound flight at MSP, with 30 minutes of complimentary waiting after a domestic landing, and the same chauffeur drives both legs whenever the schedule allows."),
        ("Can you drive from Mankato to Rochester?",
         "Yes. Mankato to Mayo Clinic in Rochester is about 90 minutes east on Highway 14, quoted as one flat fare before you confirm. Returns are timed around your last appointment, the round trip saves 10 percent, and the Cadillac Escalade is our recommendation for Highway 14 in winter."),
        ("Do you also serve St. Peter, New Ulm and Le Sueur?",
         "Yes. St. Peter, New Ulm, Le Sueur, Eagle Lake and the towns along Highway 169 and Highway 14 are all normal rides for us, quoted flat before you confirm. St. Peter to MSP takes about 75 minutes and New Ulm about 100 minutes, and dispatch is staffed 24 hours a day."),
        ("Can you meet a Mankato-bound guest at MSP with a name sign?",
         "Yes. Meet & Greet is $15. The chauffeur waits at baggage claim with a name sign, helps with luggage and walks with your guest to the car for the 85-minute ride to Mankato. We track the flight, and 30 minutes of waiting after a domestic landing is included at no charge."),
    ],
}
