# Page specs for Total Town Car Service, service pages batch B:
# point-to-point, group, flight crew, chauffeur service Minneapolis, Mall of America.
# Original copy. Fleet is exactly three vehicles (Escalade 6, S-Class 3, Continental 3).

R = {
 'airport':   ('airport-service.html', 'Airport Transfers', 'MSP arrivals and departures, flight-tracked.'),
 'black':     ('msp-airport-black-car-service.html', 'MSP Airport Black Car', 'Terminal-by-terminal pickup, fixed fares.'),
 'pickup':    ('airport-pickup.html', 'Airport Pickup', 'Baggage claim to your door, timed to your flight.'),
 'mpls':      ('minneapolis-car-service.html', 'Minneapolis Black Car', 'Private, pre-arranged, chauffeur-driven.'),
 'corp':      ('corporate-transportation.html', 'Corporate Travel', 'Executive rides, accounts and invoicing.'),
 'limo':      ('limousine-service-minneapolis.html', 'Limo Service', 'The chauffeured standard in an Escalade or S-Class.'),
 'hourly':    ('hourly-car-service.html', 'Hourly Car Service', 'A car and chauffeur for a block of time.'),
 'chauffeur': ('private-chauffeur-service.html', 'Private Chauffeur', 'As-directed driving for a full day.'),
 'p2p':       ('point-to-point-transportation.html', 'Point to Point', 'Door to door, one flat rate.'),
 'group':     ('group-transportation.html', 'Group Transportation', 'Multi-vehicle coordination for larger parties.'),
 'downtown':  ('downtown-minneapolis.html', 'Downtown Minneapolis', 'Hotels, stadiums, theaters, curb to door.'),
 'crew':      ('flight-crew-charter-service.html', 'Flight Crew Charter', 'Crew transport built around report times.'),
 'mayo':      ('rochester-mayo-clinic.html', 'Rochester & Mayo Clinic', 'Twin Cities to Rochester, private and direct.'),
 'chmpls':    ('chauffeur-service-minneapolis.html', 'Chauffeur Service', 'A dedicated professional, not just a ride.'),
 'moa':       ('mall-of-america-car-service.html', 'Mall of America', 'Bloomington, MOA and MSP, door to door.'),
 'area':      ('service-areas.html', 'Service Area', 'Every city we serve, with a page for each.'),
 'prom':      ('prom-homecoming.html', 'Prom & Homecoming', 'Safe, stylish rides for the big night.'),
 'concert':   ('concert-events.html', 'Concerts & Events', 'Arrive and leave without the parking.'),
 'wine':      ('wine-brewery-tours.html', 'Wine & Brewery Tours', 'A chauffeur for the whole tasting day.'),
 'contact':   ('contact.html', 'Contact', 'Dispatch answers 24/7.'),
}

LINK = 'class="text-gold-400 hover:text-gold-300 underline underline-offset-2"'

PAGES = [

# ---------------------------------------------------------------- 1. Point-to-point transportation
dict(
    file='point-to-point-transportation.html',
    title='Point-to-Point Car Service Minneapolis | Total Town Car Service',
    title_short='Point-to-Point Transportation',
    meta='Point-to-point transportation across Minneapolis, Saint Paul and every suburb. One flat rate quoted before you confirm, $15 extra stops, round trips save 10%.',
    keywords='point to point car service Minneapolis, door to door transportation Twin Cities, flat rate car service Minneapolis, private car service Saint Paul, black car point to point',
    service_type='Point-to-point car service',
    eyebrow='Door to Door · Flat Rate · Twin Cities',
    h1='Point-to-Point Transportation, <span class="gold-text">One Flat Rate</span>',
    lede='Any address to any other address across the Twin Cities, in a black Escalade, S-Class or Continental with a professional chauffeur. You see the full fare before you confirm, and it does not move.',
    image='images/site/svc-point-to-point.webp',
    image_alt='Chauffeur holding the rear door of a black Lincoln Continental as a smiling woman steps onto the sidewalk of a tree-lined Minneapolis street',
    image_caption='Your Door · Their Door · One Price',
    image_prompt='a brand-new 2026 black Lincoln Continental sedan (horizontal chrome mesh grille, full-width LED taillights, dark limousine-tinted windows) parallel-parked at the curb on a tree-lined street in the Kenwood neighborhood of Minneapolis, autumn maples overhead, a smiling woman in a camel coat stepping onto the sidewalk in three-quarter view with her face visible, a chauffeur in a dark suit holding the front-hinged rear door open, warm late-afternoon light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
    intro_eyebrow='What Point to Point Means',
    intro_h2='A private car from where you are to where you need to be',
    intro=[
        'Point-to-point is the simplest thing we do, and the one people book most often. You give us a pickup address, a drop-off address and a time. We assign a chauffeur and a vehicle, quote you one flat fare based on the route, and show up early. There is no meter, no surge, no guessing while you watch a map. The number you saw when you booked is the number you pay, whether traffic on 35W cooperates or not.',
        'It works for a dinner reservation in the North Loop, a morning meeting in Saint Paul, a ride home from a hospital, or a visit across town to family. It also works for longer legs, such as Minneapolis to Rochester or Duluth, quoted the same way. If you need to stop along the way, add it during booking for $15 per stop. If you already know you are coming back, book the return at the same time and the round trip saves 10%.',
        'Every point-to-point ride is private. The vehicle is yours alone from the moment your chauffeur pulls up to the moment you step out, with no other passengers and no detours you did not ask for. That is the difference between a private car service and a ride shared with whoever a rideshare app happened to find nearby, and it is the reason our regular clients stopped guessing.',
    ],
    bullets_eyebrow='What Is Included',
    bullets_h2='Everything a flat fare should cover',
    bullets_lede='No add-ons hiding behind the confirmation button. Here is what every point-to-point reservation includes.',
    bullets=[
        ('One fare, quoted first', 'The full price appears before you confirm, calculated from your route. Traffic, weather and the time you arrive do not change it.'),
        ('A professional chauffeur', 'Vetted, licensed and dressed for the occasion. Your chauffeur handles the doors and the bags and knows the Twin Cities without a phone propped on the dash.'),
        ('Extra stops for $15 each', 'Pick up a colleague, drop a friend, swing by the office for a forgotten laptop. Add as many stops as you need at booking.'),
        ('Round trips save 10%', 'Book the outbound and the return together and the total drops by ten percent. Same chauffeur whenever the schedule allows.'),
        ('Free cancellation to 24 hours', 'Plans change. Cancel up to 24 hours before pickup at no charge, online or with a quick call to dispatch.'),
        ('Pay your way', 'Pay online by card through Stripe when you book, or settle with your chauffeur at the end of the ride. Either way, the fare is the same.'),
    ],
    steps_eyebrow='How It Works',
    steps_h2='Booked in about two minutes',
    steps=[
        ('Enter both addresses', 'Pickup, drop-off and any stops in between. Choose the Escalade, S-Class or Continental and your date and time.'),
        ('See the flat fare', 'The price is calculated from the route and shown in full before you confirm. Nothing is added later.'),
        ('Confirm and relax', 'You get a confirmation by email and text. Your chauffeur is assigned and reaches out before pickup with their name and vehicle.'),
        ('Step out at the door', 'Your chauffeur arrives early, loads your bags and takes you straight to the drop-off. That is the whole ride.'),
    ],
    faq=[
        ('How is the fare calculated?', 'By the distance and route between your pickup and drop-off, plus any extra stops at $15 each. The fare is shown in full before you confirm and stays fixed regardless of traffic or how long the drive takes.'),
        ('Can I add a stop after I have booked?', 'Yes. Call dispatch at (612) 999-5382 and we will add it to the reservation for $15. If you ask your chauffeur during the ride, they can add it as well, though calling ahead keeps the schedule cleaner.'),
        ('How far ahead do I need to book?', 'Online bookings need at least two hours of notice. If you need a car sooner than that, call dispatch and we will tell you honestly whether we can be there in time.'),
        ('Does point-to-point cover long-distance trips?', 'It does. Minneapolis to Rochester, Duluth, St. Cloud or Mankato is quoted as one flat point-to-point fare, so you know the full cost before you leave the driveway.'),
        ('Is this different from hourly service?', 'Yes. Point-to-point is priced for a specific route, so it suits a ride with a clear destination. If you want the car to wait or make several undecided stops, hourly as-directed service with a three-hour minimum is the better fit.'),
        ('Which vehicle should I choose?', 'The Continental and S-Class each seat three with three bags, and the Escalade seats six with six bags. For one or two people the sedans are ideal. For four or more, or a lot of luggage, choose the Escalade.'),
    ],
    related=[R['hourly'], R['mpls'], R['airport'], R['mayo']],
    cta_h2='Two addresses. One fare. Done.',
    cta_p='Book your point-to-point ride online in a couple of minutes, or call (612) 999-5382 and dispatch will set it up for you.',
),

# ---------------------------------------------------------------- 2. Group transportation
dict(
    file='group-transportation.html',
    title='Group Transportation Minneapolis | Multi-Car | Total Town Car Service',
    title_short='Group Transportation',
    meta='Group transportation in Minneapolis and Saint Paul. Up to six in one Escalade, larger parties in two or three coordinated vehicles, one contact, one bill.',
    keywords='group transportation Minneapolis, group car service Twin Cities, multi vehicle transportation MSP, sports team transportation Minneapolis, corporate offsite transportation, wedding guest shuttle Minneapolis',
    service_type='Group transportation',
    eyebrow='Groups · Teams · Coordinated Vehicles',
    h1='Group Transportation, <span class="gold-text">Coordinated by One Dispatcher</span>',
    lede='Up to six travel together in the Escalade. Larger parties move in two or three vehicles dispatched as a set, with one point of contact, one schedule and one bill. Call for groups over six and we will plan it with you.',
    image='images/site/svc-group.webp',
    image_alt='Black Cadillac Escalade and Mercedes S-Class staged nose to tail at a downtown Minneapolis hotel entrance with a group of smiling travelers on the sidewalk',
    image_caption='Two Vehicles · One Contact · One Schedule',
    image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb with a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) directly behind it, outside a downtown Minneapolis hotel on Nicollet Mall, six smiling adults on the sidewalk facing the camera with roller bags, a chauffeur holding the Escalade\'s front-hinged rear door open, overcast morning. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
    intro_eyebrow='How We Move Groups',
    intro_h2='Right-sized vehicles, dispatched together',
    intro=[
        'Our fleet is three vehicles: a Cadillac Escalade for up to six passengers with six bags, and a Mercedes-Benz S-Class and Lincoln Continental for up to three each. For a party of six or fewer, the Escalade is the answer, and you book it online like any other ride. For larger groups, we do not squeeze anyone in and we do not send you elsewhere. We dispatch two or three vehicles together, timed to the same pickup and the same destination, so the group arrives as a group.',
        'The coordination is the part that matters. One dispatcher owns your reservation from the first call to the last drop-off. Your chauffeurs are briefed together, arrive together, and stay in touch with each other on the road. You get a single point of contact, a single confirmation and a single invoice, rather than three separate bookings you have to reconcile in a parking lot. Pickups can be simultaneous, or staggered when your group is leaving from more than one address.',
        'This is how we handle sports teams heading to a tournament, wedding guests moving between the hotel and the venue, corporate offsites leaving a downtown office at once, and family reunions collecting relatives from MSP on the same afternoon. Groups over six are arranged by phone rather than online, so we can walk through the timing, the addresses and the luggage with you before anything is confirmed.',
    ],
    bullets_eyebrow='Who Books Group Service',
    bullets_h2='Built for parties that need to arrive together',
    bullets=[
        ('Sports teams and clubs', 'Players, coaches and gear moved in the same window to a rink, field or tournament hotel, with room for equipment bags in the Escalade.'),
        ('Wedding guests', 'Out-of-town guests shuttled between hotels, the ceremony and the reception on a schedule you set once. The wedding party itself has its own page.'),
        ('Corporate offsites', 'A leadership team leaving the office at the same time, riding to the retreat and returning together, billed to one account with one receipt.'),
        ('Family reunions and celebrations', 'Relatives arriving on different flights collected at MSP and delivered to the same address, with car seats installed where needed.'),
        ('Conference and event delegations', 'Attendees moved between the hotel, the convention center and dinner without anyone waiting on a rideshare app.'),
        ('Airport groups with luggage', 'Six bags fit in the Escalade. For a group with more, we add a sedan so nothing rides on a lap.'),
    ],
    steps_eyebrow='Planning a Group',
    steps_h2='How a multi-vehicle booking comes together',
    steps=[
        ('Tell us the headcount', 'Call (612) 999-5382 with how many people, how many bags, the pickup and destination and the time you need to arrive.'),
        ('We size the fleet', 'Dispatch pairs the right vehicles, usually the Escalade plus one or two sedans, and quotes a flat fare for the whole set before you confirm.'),
        ('One confirmation, one contact', 'You receive a single confirmation listing every vehicle and chauffeur, and one dispatcher who answers your calls before and during the trip.'),
        ('Everyone arrives together', 'Chauffeurs stage early, load the group and travel in convoy or on a staggered plan, depending on what you asked for.'),
    ],
    faq=[
        ('What is the largest group you can carry in one vehicle?', 'Six passengers with six bags in the Cadillac Escalade. The S-Class and Continental each carry three. Anything larger than six is handled with two or three vehicles dispatched together.'),
        ('How do you keep multiple vehicles on the same schedule?', 'One dispatcher plans the trip and briefs every chauffeur on the same pickup time, route and destination. The chauffeurs stay in contact on the road, and dispatch tracks all of them, so you never have to relay messages between cars.'),
        ('Can pickups happen at different addresses?', 'Yes. We can collect parts of the group from separate hotels or homes on a staggered plan and bring everyone to one destination at the same time. Tell us each address when you call.'),
        ('Do we get one bill for all the vehicles?', 'Yes. A group reservation is one booking with one confirmation and one invoice, whether you pay online by card or with the chauffeur at the end.'),
        ('How much notice do you need for a group?', 'Two to three days is comfortable for most multi-vehicle bookings. Around graduation weekends, major games and holidays, a week gives us the best chance of lining up every vehicle you need.'),
        ('Can a group book hourly instead of point to point?', 'It can. If the group is moving between several venues over an evening, hourly as-directed service with a three-hour minimum keeps the vehicles with you the whole time, quoted at booking.'),
    ],
    related=[R['corp'], R['airport'], R['hourly'], R['concert']],
    cta_h2='Tell us the headcount. We will handle the rest.',
    cta_p='Groups of six or fewer can book the Escalade online now. For larger parties, call (612) 999-5382 and dispatch will build the plan with you.',
    cta1='Call to Plan Your Group',
),

# ---------------------------------------------------------------- 3. Flight crew charter service
dict(
    file='flight-crew-charter-service.html',
    title='Flight Crew Charter Service MSP Airport | Total Town Car Service',
    title_short='Flight Crew Charter',
    meta='Flight crew charter service at MSP. Hotel-to-terminal shuttles timed to report times, recurring schedules, both terminals, monthly invoicing, larger crews.',
    keywords='flight crew transportation MSP, airline crew shuttle Minneapolis, crew car service MSP airport, hotel to terminal crew transport, airline ground transportation Minneapolis',
    service_type='Flight crew transportation',
    eyebrow='Airline Crews · Both Terminals · Recurring Schedules',
    h1='Flight Crew Charter Service, <span class="gold-text">Timed to Report</span>',
    lede='Private crew transport between Twin Cities hotels and MSP, scheduled around report times rather than around traffic guesses. Recurring runs, invoiced monthly, with a dispatcher who knows your rotation.',
    image='images/site/svc-flight-crew.webp',
    image_alt='Black Mercedes-Benz S-Class at the MSP Terminal 1 departures curb at dawn with a smiling pilot and flight attendant stepping onto the sidewalk',
    image_caption='Report Time · Minus Twenty · Every Rotation',
    image_prompt='a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) parallel-parked at the departures curb of MSP Terminal 1 Lindbergh at dawn, the glass facade and concrete canopy behind, a smiling pilot in a plain navy uniform and a smiling flight attendant in navy facing the camera as they step onto the sidewalk with black roller bags, a chauffeur closing the trunk, pale pink sky, wet pavement. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
    intro_eyebrow='Crew Transport Done Properly',
    intro_h2='A shuttle that understands what a report time means',
    intro=[
        'A crew that misses report time is not a small problem for anyone. Our flight crew service exists to remove that risk. Give us the hotel, the terminal and the report time, and we schedule the pickup backward from it with a margin that accounts for the hour, the weather and the walk from the curb to the crew entrance. Your chauffeur is staged in the hotel driveway before the crew comes down, and dispatch is watching the run the whole way.',
        'We run to both MSP terminals, Terminal 1 Lindbergh and Terminal 2 Humphrey, and to the crew hotels across Bloomington, downtown Minneapolis, the airport corridor and Saint Paul. Recurring rotations are loaded once and repeated, so a scheduler is not rebooking the same Tuesday shuttle every week. Changes come through by phone or email and are confirmed back the same way.',
        'Crews of three ride in the S-Class or Continental. Larger crews, or a pilot group and a cabin crew leaving at the same time, ride in the Escalade or in two vehicles dispatched together with one point of contact. Everything is invoiced monthly to the airline, the hotel or the crew scheduling company, with each run itemized by date and vehicle so accounting has nothing to chase.',
    ],
    bullets_eyebrow='Why Crews Book Us',
    bullets_h2='What a crew shuttle needs to get right',
    bullets=[
        ('Scheduled from the report time', 'You tell us when the crew reports. We calculate the pickup, add a margin for the hour and the weather, and stage the car before it is needed.'),
        ('Both terminals, every gate area', 'Lindbergh or Humphrey, crew entrance or curb, arrivals or departures level. Your chauffeurs know exactly where each airline reports.'),
        ('Recurring schedules', 'Weekly rotations are entered once and repeated automatically. Send changes when they come through and we adjust the standing plan.'),
        ('Inbound pickups tracked to the aircraft', 'For crews landing at MSP, the pickup follows the flight. Early or late, the car is waiting when the crew clears the terminal.'),
        ('Multi-vehicle for larger crews', 'Up to six in the Escalade, or two vehicles dispatched together for a full wide-body crew, with one dispatcher coordinating both.'),
        ('Monthly invoicing', 'Every run itemized by date, flight, hotel and vehicle on one monthly statement, ready for airline or agency accounting.'),
    ],
    faq=[
        ('How early do you arrive for a crew pickup?', 'Typically the chauffeur is staged at the hotel 10 to 15 minutes before the scheduled pickup, and the pickup itself is set with enough margin to reach the terminal comfortably ahead of the report time.'),
        ('Can you handle a full crew of more than six?', 'Yes. Larger crews ride in two or three vehicles dispatched together, timed to the same report. One dispatcher coordinates all of them, so the crew is not managing separate cars.'),
        ('Do you serve both MSP terminals?', 'We do. Terminal 1 Lindbergh and Terminal 2 Humphrey are both regular runs, and our chauffeurs know the crew reporting points and pickup areas at each one.'),
        ('How are recurring crew schedules set up?', 'Send the rotation once by email or phone. We load each run as a standing reservation and confirm it back. When the schedule changes, send the update and we adjust the affected dates.'),
        ('How is crew transportation billed?', 'Monthly, on a single itemized invoice to the airline, hotel or scheduling company. Individual crew members do not need to pay at the curb or file expense reports.'),
        ('What if a flight arrives late and the crew misses the planned pickup?', 'Inbound pickups are tracked against the flight, so the car moves with the delay. There is no charge for waiting on a delayed aircraft.'),
    ],
    related=[R['airport'], R['corp'], R['pickup'], R['group']],
    cta_h2='Give us the rotation. We will keep it on time.',
    cta_p='Call (612) 999-5382 or email totaltowncarservice@gmail.com to set up crew transport, recurring runs and monthly invoicing.',
    cta1='Set Up Crew Service',
),

# ---------------------------------------------------------------- 4. Chauffeur service in Minneapolis
dict(
    file='chauffeur-service-minneapolis.html',
    title='Chauffeur Service in Minneapolis, MN | Total Town Car Service',
    title_short='Chauffeur Service',
    meta='Professional chauffeur service in Minneapolis. Vetted, uniformed chauffeurs, door service, route knowledge and discretion in an Escalade, S-Class or Continental',
    keywords='chauffeur service Minneapolis, professional chauffeur Twin Cities, chauffeured car service Minneapolis, private driver Minneapolis, executive chauffeur MSP',
    service_type='Chauffeur service',
    eyebrow='Professional Chauffeurs · Since 1991 · Minneapolis',
    h1='Chauffeur Service in Minneapolis, <span class="gold-text">Not Just a Driver</span>',
    lede='A chauffeur is a trained professional whose job is the whole experience, not only the miles. Vetted, uniformed, at the door before you reach it, and quiet when you would rather work or think.',
    image='images/site/svc-chauffeur-mpls.webp',
    image_alt='Uniformed chauffeur offering a hand as a smiling woman in an evening coat steps from a black Cadillac Escalade onto the sidewalk by the Minneapolis riverfront',
    image_caption='Vetted · Uniformed · At Your Door',
    image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb on the Minneapolis riverfront in the Mill District, the Stone Arch Bridge glowing behind at blue hour, a chauffeur in a charcoal suit at the front-hinged open rear door offering his hand, a smiling woman in a black evening coat stepping onto the sidewalk facing the camera, warm streetlamp light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
    intro_eyebrow='Chauffeur vs. Driver',
    intro_h2='The difference you notice at the curb',
    intro=[
        'A driver gets you from one address to another. A chauffeur takes responsibility for everything around that. Our chauffeurs are background-checked, licensed and trained before they take a single reservation, and they present the way you would expect for a client meeting: pressed dark suit, clean vehicle, no phone in hand. They are at the rear door before you reach it, they handle every bag, and they have already planned the route, the alternate and the drop-off spot before you sit down.',
        'Route knowledge is the quiet part of the job. A chauffeur who has worked Minneapolis for years knows which downtown ramps close for events, how the Lowry Hill tunnel behaves at 5 PM, where the hotel entrance actually is versus where the app says it is, and which MSP terminal your airline uses. That knowledge shows up as the ride that simply arrives on time, without drama or a nervous glance at the clock.',
        'Discretion is the rest of it. Conversations in the back seat stay there. A chauffeur reads whether you want to talk or work, keeps the cabin at the temperature you asked for, and treats a ride to a hospital appointment with the same care as a ride to a gala. Total Town Car has held that standard since 1991, over more than 10,000 rides, and it is why our reviews read the way they do.',
    ],
    bullets_eyebrow='What a Chauffeur Does Differently',
    bullets_h2='Six habits that separate a chauffeur from a ride',
    bullets=[
        ('Vetted and licensed', 'Every chauffeur passes a background check, driving record review and in-person training before joining. You always know who is picking you up.'),
        ('Uniformed and presentable', 'Dark suit, tie and a vehicle detailed before every reservation. The first impression is the one your client or your date sees.'),
        ('Door and luggage service', 'The rear door is opened for you, bags go in and out of the trunk without you lifting them, and an umbrella appears when the weather turns.'),
        ('Route knowledge', 'Downtown closures, event traffic, hotel entrances and terminal layouts are known in advance, so the route is planned rather than improvised.'),
        ('Discretion in the cabin', 'What is said in the car stays in the car. Your chauffeur speaks when you want conversation and stays quiet when you do not.'),
        ('Early, every time', 'Chauffeurs stage ten minutes ahead of the pickup and text you their name and vehicle, so you are never waiting or wondering.'),
    ],
    faq=[
        ('What is the difference between a chauffeur and a driver?', 'A driver operates the vehicle. A chauffeur is a trained professional responsible for the whole experience: presentation, door and luggage service, route planning, punctuality and discretion. Our chauffeurs are vetted and trained to that standard before they carry a client.'),
        ('How are your chauffeurs screened?', 'Each one passes a criminal background check, a motor vehicle record review and in-person training on our service standards. Most have been with us for years, and many of our regular clients request the same chauffeur by name.'),
        ('Can I request a specific chauffeur?', 'Yes. Add the request when you book or mention it to dispatch. We honor it whenever that chauffeur is available for the date and time you need.'),
        ('Do chauffeurs help with luggage and doors?', 'Always. Your chauffeur opens the rear door, loads and unloads every bag, and walks you to the entrance when it is helpful. That is part of the service, not an upgrade.'),
        ('Which vehicles come with chauffeur service?', 'Every vehicle we operate is chauffeured: the Cadillac Escalade for up to six, the Mercedes-Benz S-Class for up to three, and the Lincoln Continental for up to three. There is no self-drive option.'),
        ('Can I book a chauffeur for a full day?', 'Yes. Hourly as-directed service keeps a chauffeur and vehicle with you for a three-hour minimum or a full day, quoted at booking. See the private chauffeur page for how that works.'),
    ],
    related=[R['chauffeur'], R['limo'], R['mpls'], R['hourly']],
    cta_h2='Ride with a professional, not a stranger.',
    cta_p='Book a chauffeured Escalade, S-Class or Continental online, or call (612) 999-5382 and dispatch will match you with the right chauffeur.',
),

# ---------------------------------------------------------------- 5. Mall of America car service
dict(
    file='mall-of-america-car-service.html',
    title='Mall of America Car Service, Bloomington | Total Town Car Service',
    title_short='Mall of America Car Service',
    meta='Private car service to and from Mall of America in Bloomington. MSP is three miles away, about ten minutes. MOA hotels, hourly shopping days, room for bags.',
    keywords='Mall of America car service, MOA to MSP airport car service, Bloomington car service, Mall of America hotel transportation, black car Mall of America, MOA airport transfer',
    service_type='Mall of America car service',
    eyebrow='Bloomington · MOA · MSP in Ten Minutes',
    h1='Mall of America Car Service, <span class="gold-text">Door to Door</span>',
    lede='Private chauffeured rides between Mall of America, the hotels around it and MSP Airport three miles up the road. Flat fares, flight tracking, and enough trunk space for a full day of shopping.',
    image='images/site/svc-moa.webp',
    image_alt='Chauffeur loading shopping bags into the back of a black Cadillac Escalade as a smiling couple steps onto the sidewalk outside a Bloomington hotel near Mall of America',
    image_caption='Hotel · Mall · Terminal · Repeat',
    image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb under the covered entrance of a modern hotel in Bloomington near Mall of America, fresh snow on the landscaping, a smiling couple in wool coats facing the camera as they step onto the sidewalk carrying glossy shopping bags, a chauffeur placing a roller bag into the open rear cargo area, bright winter midday light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
    intro_eyebrow='MOA, Bloomington and the Airport',
    intro_h2='Three miles from the terminal, with a chauffeur who knows the entrances',
    intro=[
        'Mall of America sits in Bloomington about three miles from MSP Airport, roughly a ten-minute drive when the roads are clear. That short hop is one of the most common rides we run: arriving visitors heading straight from baggage claim to a hotel on the MOA campus, and departing guests who want a calm ride back to Terminal 1 or Terminal 2 with their bags already loaded. Every airport leg is flight-tracked, so an early or late landing simply moves the pickup.',
        'The hotels around the mall, along Killebrew Drive, 24th Avenue and American Boulevard, all have specific entrances and pickup lanes, and the mall itself has several. Your chauffeur knows which one to use so you are not walking a parking structure with shopping bags. For families, the Escalade carries six passengers and six bags with car seats installed on request, which matters when a day at Nickelodeon Universe or the aquarium ends with tired kids and a lot to carry.',
        'If you plan to spend the day between the mall, IKEA across the street, dinner in Bloomington and back to the hotel, book hourly instead. A chauffeur and vehicle stay with you for a three-hour minimum, quoted at booking, so purchases go straight to the trunk and you never wait at a curb for a rideshare app to find someone.',
    ],
    bullets_eyebrow='Rides Around MOA',
    bullets_h2='The trips we run most around Mall of America',
    bullets=[
        ('MSP to Mall of America', 'Ten minutes from either terminal to the mall or any hotel on the campus, flight-tracked, with complimentary wait time after you land.'),
        ('MOA hotels to the airport', 'Pickup at your hotel entrance, bags loaded, straight to the correct terminal for your airline with time to spare.'),
        ('Shopping-day hourly service', 'Keep the car for three hours or the whole day. Drop bags in the trunk between stores and move on to lunch or IKEA whenever you like.'),
        ('Downtown Minneapolis to MOA', 'About 20 minutes from the North Loop or the convention center hotels, a flat fare that does not change with traffic on 35W.'),
        ('Room for everything', 'The Escalade carries six passengers and six bags, and the S-Class and Continental carry three each. Purchases, strollers and luggage all fit.'),
        ('Families welcome', 'Child car seats installed in advance, $25 each for up to four, so the ride from the terminal to the hotel is safe from the first mile.'),
    ],
    faq=[
        ('How far is Mall of America from MSP Airport?', 'About three miles. The drive takes roughly ten minutes in normal conditions, a little longer during rush hour or heavy snow. It is one of the shortest airport rides in the Twin Cities.'),
        ('Can you pick us up at a hotel near the mall?', 'Yes. We serve every hotel on and around the MOA campus, including those along Killebrew Drive, 24th Avenue and American Boulevard, and our chauffeurs know each pickup lane.'),
        ('Do you wait while we shop?', 'With hourly service, yes. Book a three-hour minimum or a full day and your chauffeur stays with you, storing bags in the trunk between stops. Point-to-point rides are for a single drop-off.'),
        ('Will all our shopping bags fit?', 'The Escalade holds six bags in the cargo area plus whatever rides comfortably in the cabin. For a family with luggage and a serious shopping haul, it is the right choice. The sedans carry three bags each.'),
        ('Can we book a ride from MOA to downtown Minneapolis or Saint Paul?', 'Yes. Both are flat-fare point-to-point rides of roughly 20 to 25 minutes. Add a stop for $15 if you want to drop someone at a second address on the way.'),
        ('What if our flight into MSP is delayed?', 'We track it. The pickup moves with the aircraft, and you have 30 minutes of complimentary wait time on domestic arrivals and 60 on international, so there is no rush from baggage claim.'),
    ],
    related=[R['airport'], R['hourly'], R['pickup'], R['downtown']],
    cta_h2='From the terminal to the mall in ten minutes.',
    cta_p='Book your Mall of America ride online, or call (612) 999-5382 for hotel pickups, hourly shopping days and family car seats.',
),

]
