# Total Town Car Service - city page specs, batch B
# Burnsville, Lakeville, Apple Valley, Roseville, Blaine, Stillwater, Rochester, Duluth, St. Cloud, Mankato

R = {
 'airport':   ('airport-service.html', 'Airport Transfers', 'MSP arrivals and departures, flight-tracked.'),
 'black':     ('msp-airport-black-car-service.html', 'MSP Airport Black Car', 'Terminal-by-terminal pickup, fixed fares.'),
 'pickup':    ('airport-pickup.html', 'Airport Pickup', 'Baggage claim to your door, timed to your flight.'),
 'mpls':      ('minneapolis-car-service.html', 'Minneapolis Black Car', 'Private, pre-arranged, chauffeur-driven.'),
 'corp':      ('corporate-transportation.html', 'Corporate Travel', 'Executive rides, accounts and invoicing.'),
 'limo':      ('limousine-service-minneapolis.html', 'Limo Service', 'The chauffeured standard in an Escalade or S-Class.'),
 'hourly':    ('hourly-car-service.html', 'Hourly Car Service', 'A car and chauffeur for a block of time.'),
 'chauffeur': ('private-chauffeur-service.html', 'Private Chauffeur', 'As-directed driving for a full day.'),
 'p2p':       ('point-to-point-transportation.html', 'Point to Point', 'Door to door, one flat rate.'),
 'group':     ('group-transportation.html', 'Group Transportation', 'Multi-vehicle coordination for larger parties.'),
 'downtown':  ('downtown-minneapolis.html', 'Downtown Minneapolis', 'Hotels, stadiums, theaters, curb to door.'),
 'crew':      ('flight-crew-charter-service.html', 'Flight Crew Charter', 'Crew transport built around report times.'),
 'mayo':      ('rochester-mayo-clinic.html', 'Rochester & Mayo Clinic', 'Twin Cities to Rochester, private and direct.'),
 'chmpls':    ('chauffeur-service-minneapolis.html', 'Chauffeur Service', 'A dedicated professional, not just a ride.'),
 'moa':       ('mall-of-america-car-service.html', 'Mall of America', 'Bloomington, MOA and MSP, door to door.'),
 'area':      ('service-areas.html', 'Service Area', 'Every city we serve, with a page for each.'),
 'prom':      ('prom-homecoming.html', 'Prom & Homecoming', 'Safe, stylish rides for the big night.'),
 'concert':   ('concert-events.html', 'Concerts & Events', 'Arrive and leave without the parking.'),
 'wine':      ('wine-brewery-tours.html', 'Wine & Brewery Tours', 'A chauffeur for the whole tasting day.'),
 'contact':   ('contact.html', 'Contact', 'Dispatch answers 24/7.'),
}

PHOTO_END = 'Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.'
ESCALADE = 'a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows)'
SCLASS = 'a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows)'
CONTINENTAL = 'a brand-new 2026 black Lincoln Continental sedan (horizontal chrome mesh grille, full-width LED taillights, dark limousine-tinted windows)'

PAGES = [

# ---------------------------------------------------------------- Burnsville
dict(
  file='car-service-burnsville.html',
  title='Black Car Service in Burnsville, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Burnsville Car Service',
  meta='Private black car service in Burnsville, MN. Flat-rate chauffeured rides to MSP in about 20 minutes, flight tracking, 24/7 dispatch and professional drivers since 1991.',
  keywords='Burnsville car service, Burnsville black car service, Burnsville airport car service, Burnsville to MSP, chauffeur Burnsville MN, Burnsville MN limo service',
  service_type='Black car service',
  eyebrow='Burnsville · South Metro · MSP in 20 min',
  h1='Black Car Service in <span class="gold-text">Burnsville, MN</span>',
  lede='Flat-rate chauffeured rides from every Burnsville neighborhood to MSP, downtown and beyond, quoted before you confirm.',
  image='images/site/city-burnsville.webp',
  image_alt='Black Cadillac Escalade parked at the curb outside the Ames Center plaza in Burnsville, Minnesota',
  image_caption='Burnsville · South Metro · Curb to Door',
  image_prompt=ESCALADE + ' parallel-parked at the curb on the brick plaza outside a modern performing arts center in the Heart of the City district of Burnsville, Minnesota, on a golden late-summer afternoon. A businessman in his forties in a navy blazer, facing the camera and smiling, steps out of the rear passenger door onto the sidewalk holding a leather carry-on, front-hinged door open, low fountains and planters and a suburban Minnesota sky behind him. ' + PHOTO_END,
  intro_eyebrow='Serving Burnsville',
  intro_h2='From the 35W and 35E split to the terminal, without the parking ramp',
  intro=[
    'Burnsville sits at the point where I-35 divides, which makes it one of the easiest south metro cities to leave from and one of the slowest to drive through at rush hour. We pick up across the city, from Heart of the City and the Ames Center to the neighborhoods around Crystal Lake, Buck Hill and Burnsville Center, and take Highway 77 or I-35W north so you reach MSP in about 20 minutes. Your chauffeur handles the Cedar Avenue bridge and the terminal loop, and you walk straight to check-in.',
    'Corporate travelers use us for early flights out of the office parks along Burnsville Parkway and County Road 42, and for clients staying at the hotels clustered near the I-35W and Highway 13 interchange. Families book us for Buck Hill ski days with the gear in the back of the Escalade, for concerts at the Ames Center, and for appointments at Fairview Ridges Hospital when driving is not the right option that day. Every fare is quoted flat before you confirm, so the number on the quote is the number on the receipt.',
    'Because dispatch runs around the clock and every airport ride is tracked against the flight, a 4:30 AM pickup in Burnsville is as routine for us as a noon one. Book online in a couple of minutes, or call and a dispatcher will set it up while you are still packing.',
  ],
  bullets_eyebrow='Why Burnsville rides with us',
  bullets_h2='What you get on every Burnsville pickup',
  bullets=[
    ('MSP in about 20 minutes', 'Highway 77 or I-35W straight to Terminal 1 or Terminal 2, with the route chosen for the traffic that morning rather than the default map line.'),
    ('Flat fares, no surge', 'A Burnsville to MSP ride is quoted before you confirm. Rain, snow or a backup on the Cedar Avenue bridge, the price does not move.'),
    ('Flight-tracked returns', 'On the way home we watch your inbound flight, so a late landing at Lindbergh still meets a waiting chauffeur and a quiet ride back to Burnsville.'),
    ('Room for the whole trip', 'The Escalade seats six with bags, ideal for Buck Hill ski gear, a family departure from MSP, or a group night out at the Ames Center.'),
  ],
  faq=[
    ('How long is the ride from Burnsville to MSP Airport?', 'About 20 minutes in normal traffic via Highway 77 or I-35W and I-494. We build in extra time for weekday rush hour on the Cedar Avenue bridge and for winter conditions, and your chauffeur adjusts the route on the day if the split is backed up.'),
    ('Do you pick up at Burnsville Center, the Ames Center and the hotels near I-35W?', 'Yes. We serve every address in Burnsville, including the Burnsville Center area, Heart of the City, the Ames Center, Buck Hill, Fairview Ridges Hospital and the hotels around the Highway 13 and I-35W interchange. Tell us the exact entrance and your chauffeur will be waiting there.'),
    ('What does a black car from Burnsville cost?', 'Fares start at $49 for the Lincoln Continental sedan, $59 for the Mercedes-Benz S-Class executive sedan and $69 for the Cadillac Escalade SUV, plus distance. Longer trips such as Rochester or Duluth are quoted as a single flat fare before you confirm.'),
    ('Can I book a very early morning pickup in Burnsville?', 'Yes. Dispatch runs 24 hours a day and early departures from MSP are a large part of what we do in the south metro. Book online at least two hours ahead, or call for anything sooner, and your chauffeur will text when they are outside.'),
    ('Is there a discount for booking the airport ride both ways?', 'Yes. Booking your departure and your return together saves 10 percent on the total, and both legs are locked to your itinerary. If the return flight changes, tell dispatch and we retime the pickup at no charge.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Your Burnsville ride, quoted in a minute',
  cta_p='Book online with a flat fare, or call dispatch any hour and we will have a chauffeur at your door.',
  city='Burnsville', city_state='MN', drive_time='about 20 minutes',
),

# ---------------------------------------------------------------- Lakeville
dict(
  file='car-service-lakeville.html',
  title='Black Car Service in Lakeville, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Lakeville Car Service',
  meta='Private black car service in Lakeville, MN. Flat fares to MSP in about 30 minutes, flight-tracked pickups, 24/7 dispatch and chauffeurs who know the south metro.',
  keywords='Lakeville car service, Lakeville black car service, Lakeville airport car service, Lakeville to MSP, chauffeur Lakeville MN, Lakeville MN car service',
  service_type='Black car service',
  eyebrow='Lakeville · South Metro · MSP in 30 min',
  h1='Black Car Service in <span class="gold-text">Lakeville, MN</span>',
  lede='Chauffeured rides from Lakeville to MSP, downtown and across Minnesota, with one flat fare quoted up front.',
  image='images/site/city-lakeville.webp',
  image_alt='Black Lincoln Continental parked on Holyoke Avenue in downtown Lakeville, Minnesota',
  image_caption='Lakeville · Holyoke Avenue · Flat Fare',
  image_prompt=CONTINENTAL + ' parallel-parked at the curb along a small-town main street of low brick storefronts in downtown Lakeville, Minnesota, on a bright early-summer morning with hanging flower baskets on the lamp posts. A couple in their thirties, both facing the camera and smiling, step out of the rear passenger door onto the sidewalk, the man rolling a hard-shell suitcase, front-hinged door open, a water tower faintly visible in the distance. ' + PHOTO_END,
  intro_eyebrow='Serving Lakeville',
  intro_h2='The far south metro, handled like it is next door',
  intro=[
    'Lakeville is where the metro thins out into lakes and farmland, and it is exactly the kind of place where a reliable ride to the airport matters most. We pick up everywhere from historic downtown on Holyoke Avenue to the neighborhoods around Lake Marion, Antlers Park and Crystal Lake, and along the I-35 and Cedar Avenue corridors that connect the city to the rest of the Twin Cities. Your chauffeur takes I-35 north through the Burnsville split and has you at MSP in about 30 minutes.',
    'Much of our Lakeville work is business travel. Companies in the Airlake industrial park and along County Road 70 book us for early departures and for visitors flying in, and executives at the corporate headquarters on the east side of town use us for meetings downtown and at MSP. Families rely on us during Pan-O-Prog week, for prom and homecoming at Lakeville North and South, and for holiday runs when three generations and their luggage need to be at Terminal 1 at the same time.',
    'Fares from Lakeville are flat and quoted before you confirm, whether it is a 6 AM ride to the airport, a night out in Minneapolis, or a long-distance trip to Rochester or Mankato. Dispatch is awake 24 hours a day, and so are we.',
  ],
  bullets_eyebrow='Why Lakeville rides with us',
  bullets_h2='What you get on every Lakeville pickup',
  bullets=[
    ('MSP in about 30 minutes', 'I-35 north through the Burnsville split to I-494 and the terminals, with your chauffeur watching traffic and choosing the Cedar Avenue route when it is faster.'),
    ('Quoted before you confirm', 'One flat fare from any Lakeville address, from Airlake to Lake Marion, with no surge and no meter running while you sit in rush hour traffic.'),
    ('Timed to the flight', 'We track your flight in both directions, so a departure from Lakeville leaves at the right time and a return pickup waits for a late landing.'),
    ('Three cars, one standard', 'Choose the Lincoln Continental sedan, the Mercedes-Benz S-Class executive sedan or the six-seat Escalade for family trips from Antlers Park to MSP.'),
  ],
  faq=[
    ('How long does it take to get from Lakeville to MSP?', 'About 30 minutes in normal traffic on I-35 and I-494, a little longer from the far south and west sides of the city. Weekday mornings through the Burnsville split can add time, so we schedule your pickup with a comfortable cushion built in.'),
    ('Do you serve the Airlake industrial park and downtown Lakeville?', 'Yes. We pick up at any Lakeville address, including Airlake and the businesses along County Road 70, downtown Holyoke Avenue, the lake neighborhoods and the hotels near the I-35 exits. Corporate accounts with monthly invoicing are available for companies with regular travelers.'),
    ('What does a car from Lakeville to the airport cost?', 'Sedan fares start at $49, the S-Class executive sedan at $59 and the Escalade SUV at $69, plus distance from your address. Long-distance trips to Rochester, Mankato, St. Cloud or Duluth are quoted as one flat fare before you confirm.'),
    ('Can you handle a 5 AM pickup in Lakeville?', 'Yes. Early flights are the most common Lakeville booking we take. Dispatch is staffed 24 hours a day, the chauffeur is assigned the night before, and you receive a text when the car is outside. Book online two hours or more ahead, or call for something sooner.'),
    ('Do I save anything by booking the return ride too?', 'Yes. Booking both directions at once saves 10 percent on the whole trip. Your return pickup is tracked against the inbound flight, and if the flight changes you simply tell dispatch and we adjust the time at no charge.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['corp']],
  cta_h2='Book your Lakeville ride',
  cta_p='Flat fare, professional chauffeur, on time from Holyoke Avenue to the terminal door.',
  city='Lakeville', city_state='MN', drive_time='about 30 minutes',
),

# ---------------------------------------------------------------- Apple Valley
dict(
  file='car-service-apple-valley.html',
  title='Black Car Service in Apple Valley, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Apple Valley Car Service',
  meta='Private black car service in Apple Valley, MN. Flat fares to MSP in about 25 minutes via Cedar Avenue, flight tracking, 24/7 dispatch and professional chauffeurs.',
  keywords='Apple Valley car service, Apple Valley black car service, Apple Valley airport car service, Apple Valley to MSP, chauffeur Apple Valley MN, Apple Valley MN car service',
  service_type='Black car service',
  eyebrow='Apple Valley · South Metro · MSP in 25 min',
  h1='Black Car Service in <span class="gold-text">Apple Valley, MN</span>',
  lede='Chauffeured rides from Apple Valley to MSP, downtown and across the state, with the fare fixed before you book.',
  image='images/site/city-apple-valley.webp',
  image_alt='Black Mercedes-Benz S-Class parked near the entrance plaza of the Minnesota Zoo in Apple Valley',
  image_caption='Apple Valley · Cedar Avenue · Fixed Fare',
  image_prompt=SCLASS + ' parallel-parked at the curb of a wide entrance plaza framed by tall pines and a modern timber-and-stone entry pavilion at the Minnesota Zoo in Apple Valley, Minnesota, on a clear autumn morning with maples turning red. A mother and two children in their early school years, all facing the camera and smiling, step out of the rear passenger door onto the sidewalk, front-hinged door open, the mother holding a small backpack. ' + PHOTO_END,
  intro_eyebrow='Serving Apple Valley',
  intro_h2='Straight up Cedar Avenue to the terminal',
  intro=[
    'Apple Valley has one of the most direct airport routes in the south metro. Cedar Avenue runs from the city straight north over the Minnesota River to Highway 77 and the MSP terminals, and in normal traffic your chauffeur covers it in about 25 minutes. We pick up everywhere in the city, from the neighborhoods around Lebanon Hills and Cobblestone Lake to the apartments and townhomes along the Cedar Avenue transit corridor and the retail district on County Road 42.',
    'The Minnesota Zoo brings visitors from all over the region, and we regularly bring families and out-of-town guests from downtown hotels and MSP to the zoo gates and back again. Corporate travelers at the headquarters campuses along 147th Street and Cedar Avenue book us for early flights and client visits, and residents use us for summer concerts at Kelley Park, evenings at the Ames Center in neighboring Burnsville, and appointments at the clinics in Apple Valley and Burnsville.',
    'Every ride is quoted as a flat fare before you confirm, and airport pickups are tracked against the flight so a delay costs you nothing. Dispatch is staffed 24 hours a day for early departures and late arrivals.',
  ],
  bullets_eyebrow='Why Apple Valley rides with us',
  bullets_h2='What you get on every Apple Valley pickup',
  bullets=[
    ('Cedar Avenue, done for you', 'Your chauffeur takes Cedar and Highway 77 straight to Terminal 1 or 2, or swings over to I-35W if the bridge is slow that morning.'),
    ('One flat fare', 'From Lebanon Hills or Cobblestone Lake to MSP, the price is set before you confirm and does not change with weather, traffic or time of day.'),
    ('Zoo days and family trips', 'The Escalade seats six with strollers and bags, ideal for a Minnesota Zoo visit with grandparents or a family departure from MSP.'),
    ('Watched flights, quiet returns', 'We track your inbound flight and meet you at baggage claim or the curb, then take you home to Apple Valley without a second thought.'),
  ],
  faq=[
    ('How far is Apple Valley from MSP Airport?', 'About 25 minutes in normal traffic, straight up Cedar Avenue and Highway 77 to either terminal. Morning rush hour on the Cedar Avenue bridge can add ten minutes, which we build into your scheduled pickup time.'),
    ('Do you pick up and drop off at the Minnesota Zoo?', 'Yes. We regularly bring guests to the Minnesota Zoo from downtown Minneapolis, Saint Paul and MSP, and take Apple Valley families there for the day. Give us the arrival time you want and we will handle the drop-off at the main entrance and the return.'),
    ('What does a black car from Apple Valley cost?', 'Fares start at $49 for the Lincoln Continental sedan, $59 for the Mercedes-Benz S-Class executive sedan and $69 for the Cadillac Escalade SUV, plus distance. Trips to Rochester, Mankato and other long-distance destinations are quoted as one flat fare before you confirm.'),
    ('Can I get a ride from Apple Valley before dawn?', 'Yes. Dispatch is awake 24 hours a day and early flights are the most common booking we take in the south metro. Book online at least two hours ahead or call for anything sooner, and your chauffeur will text when the car is outside.'),
    ('Is there a discount for a round trip to the airport?', 'Yes. Booking your departure and return together saves 10 percent on the total. Both legs are tied to your flights, so if the return lands late your chauffeur is still waiting, and if it changes we retime the pickup at no charge.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Apple Valley to MSP, one flat fare',
  cta_p='Book online in a couple of minutes or call dispatch any hour and a chauffeur will be at your door.',
  city='Apple Valley', city_state='MN', drive_time='about 25 minutes',
),

# ---------------------------------------------------------------- Roseville
dict(
  file='car-service-roseville.html',
  title='Black Car Service in Roseville, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Roseville Car Service',
  meta='Private black car service in Roseville, MN. Flat fares to MSP in about 25 minutes, hotel and Rosedale pickups, flight tracking, 24/7 dispatch and professional chauffeurs.',
  keywords='Roseville car service, Roseville black car service, Roseville airport car service, Roseville to MSP, chauffeur Roseville MN, Rosedale car service',
  service_type='Black car service',
  eyebrow='Roseville · North Metro · MSP in 25 min',
  h1='Black Car Service in <span class="gold-text">Roseville, MN</span>',
  lede='Chauffeured rides from Roseville hotels, homes and offices to MSP, both downtowns and beyond, quoted before you confirm.',
  image='images/site/city-roseville.webp',
  image_alt='Black Cadillac Escalade parked at the curb outside a hotel entrance near Rosedale Center in Roseville, Minnesota, in winter',
  image_caption='Roseville · Rosedale · Both Downtowns',
  image_prompt=ESCALADE + ' parallel-parked at the curb beside a snowy suburban park with an outdoor speed-skating oval and bare oak trees in Roseville, Minnesota, on a crisp bright winter afternoon with fresh snow on the ground. A father in a wool overcoat and his teenage daughter carrying a skate bag, both facing the camera and smiling, step out of the rear passenger door onto the cleared sidewalk, front-hinged door open, skaters small in the distance behind them. ' + PHOTO_END,
  intro_eyebrow='Serving Roseville',
  intro_h2='Between the two downtowns, with the airport 25 minutes away',
  intro=[
    'Roseville sits in the middle of everything, ten minutes from downtown Minneapolis, ten from downtown Saint Paul, and about 25 minutes from MSP by I-35W and Highway 62. That location is why so many hotels line County Road D, Cleveland Avenue and Highway 36 around Rosedale Center, and why we spend so much time in the city. We pick up at every hotel and address in Roseville, from the neighborhoods off Lexington and Hamline to the office parks along Highway 36 and County Road C.',
    'Corporate travelers book us for morning flights and for meetings in either downtown, and hotel guests use us for shopping trips to Rosedale and Har Mar, dinner in Saint Paul, and the short ride to the Minnesota State Fairgrounds when the fair or a summer event is on. Residents rely on us for winter mornings at the Roseville OVAL and Central Park, for concerts and games downtown, and for a comfortable ride to Rochester or Duluth when the trip is long.',
    'Every fare is flat and quoted before you confirm, airport pickups are tracked against the flight, and dispatch answers 24 hours a day. Roseville rides are simple to book and simpler to take.',
  ],
  bullets_eyebrow='Why Roseville rides with us',
  bullets_h2='What you get on every Roseville pickup',
  bullets=[
    ('Hotel row, covered', 'We know the entrances along County Road D, Cleveland Avenue and Highway 36 near Rosedale, and your chauffeur is at the right door on time.'),
    ('MSP in about 25 minutes', 'I-35W south to Highway 62 and the terminals, or Snelling to Highway 5 when traffic makes it the faster choice.'),
    ('Both downtowns, one fare', 'Minneapolis or Saint Paul, the ride from Roseville is quoted flat before you confirm, with no surge for game nights or bad weather.'),
    ('Winter-ready fleet', 'The Escalade handles snow days on Highway 36 and has room for six with skate bags, luggage or a family heading to the State Fair.'),
  ],
  faq=[
    ('How long is the drive from Roseville to MSP?', 'About 25 minutes in normal traffic, usually I-35W south to Highway 62 and the terminals. During rush hour or snow we build extra time into your pickup, and your chauffeur may use Snelling Avenue and Highway 5 if it is moving faster that day.'),
    ('Do you pick up at the hotels near Rosedale Center?', 'Yes. We serve every hotel in Roseville, including the properties along County Road D, Cleveland Avenue and Highway 36, as well as Rosedale Center, Har Mar Mall and any home or office in the city. Tell us the hotel name and we handle the rest.'),
    ('What does a black car from Roseville cost?', 'Fares start at $49 for the Lincoln Continental sedan, $59 for the Mercedes-Benz S-Class executive sedan and $69 for the Cadillac Escalade SUV, plus distance. Longer trips such as Rochester, Duluth or St. Cloud are quoted as one flat fare before you confirm.'),
    ('Can you take me to the Minnesota State Fair from Roseville?', 'Yes. The fairgrounds are minutes from Roseville and we run fair rides every day of the fair, with drop-off as close to the gates as traffic control allows and a scheduled or on-call pickup for the ride home.'),
    ('Do early morning pickups and round trips work the same way?', 'Yes. Dispatch is staffed 24 hours a day, so a 4 AM pickup in Roseville is routine, and booking your departure and return together saves 10 percent on the total. Book online at least two hours ahead, or call for anything sooner.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Book your Roseville ride',
  cta_p='Hotels, homes and offices across Roseville, one flat fare and a chauffeur who is early.',
  city='Roseville', city_state='MN', drive_time='about 25 minutes',
),

# ---------------------------------------------------------------- Blaine
dict(
  file='car-service-blaine.html',
  title='Black Car Service in Blaine, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Blaine Car Service',
  meta='Private black car service in Blaine, MN. Flat fares to MSP in about 35 minutes, National Sports Center and TPC Twin Cities pickups, flight tracking and 24/7 dispatch.',
  keywords='Blaine car service, Blaine black car service, Blaine airport car service, Blaine to MSP, chauffeur Blaine MN, National Sports Center car service',
  service_type='Black car service',
  eyebrow='Blaine · North Metro · MSP in 35 min',
  h1='Black Car Service in <span class="gold-text">Blaine, MN</span>',
  lede='Chauffeured rides from Blaine to MSP, downtown and the rest of Minnesota, quoted flat before you confirm.',
  image='images/site/city-blaine.webp',
  image_alt='Black Lincoln Continental parked at the curb beside the soccer fields of the National Sports Center in Blaine, Minnesota',
  image_caption='Blaine · Sports Center · Flat Fare',
  image_prompt=CONTINENTAL + ' parallel-parked at the curb beside a vast complex of green soccer fields and a large arena in the background at the National Sports Center in Blaine, Minnesota, on a bright midsummer evening with long shadows. A teenage boy in a sports jersey holding a hockey bag and his mother beside him, both facing the camera and smiling, step out of the rear passenger door onto the sidewalk, front-hinged door open, a wide open prairie sky above. ' + PHOTO_END,
  intro_eyebrow='Serving Blaine',
  intro_h2='Tournaments, tee times and early flights, all from the north metro',
  intro=[
    'Blaine is the north metro city that visitors know best. The National Sports Center draws teams and families from across the country for soccer, hockey and skating events, TPC Twin Cities hosts a PGA Tour stop every summer, and the corporate campuses along Highway 65 and Lexington Avenue bring executives through year round. We pick up at all of it, along with every neighborhood from The Lakes to the older streets near Northtown, and reach MSP in about 35 minutes by I-35W or Highway 65.',
    'Teams and tournament families book us for the airport at both ends of a weekend, often as two or three vehicles dispatched together when the group is larger than six. Golf guests use us between the hotels near Highway 65, the course and downtown Minneapolis. Corporate travelers at the headquarters campuses in Blaine and neighboring Ham Lake rely on us for early departures, and residents book us for concerts, games and the occasional long trip to Duluth or St. Cloud.',
    'Every fare is flat and quoted before you confirm. Airport pickups are tracked against the flight, dispatch answers 24 hours a day, and your chauffeur knows the north metro well enough to get you around a backup on 35W.',
  ],
  bullets_eyebrow='Why Blaine rides with us',
  bullets_h2='What you get on every Blaine pickup',
  bullets=[
    ('Sports Center pickups', 'We know the rinks, fields and lots at the National Sports Center and stage the car where your team can find it after the last game.'),
    ('MSP in about 35 minutes', 'I-35W south straight through Minneapolis to the terminals, or Highway 65 and Highway 610 when the traffic pattern favors it that day.'),
    ('Groups larger than six', 'Tournament families and golf outings get two or three cars dispatched together, one booking and one arrival time at the terminal.'),
    ('Flat fares, quoted first', 'From Blaine to MSP, downtown or TPC Twin Cities, the fare is fixed before you confirm and does not surge on tournament weekends.'),
  ],
  faq=[
    ('How long does it take to get from Blaine to MSP?', 'About 35 minutes in normal traffic, usually I-35W south through downtown Minneapolis to Highway 62 and the terminals. Rush hour and construction on 35W can add time, so we schedule your pickup with a cushion and your chauffeur watches conditions that morning.'),
    ('Do you pick up at the National Sports Center and TPC Twin Cities?', 'Yes. We serve the National Sports Center, its rinks and fields, TPC Twin Cities, the hotels along Highway 65 and I-35W, and every home and office in Blaine. Send us the arena or lot you will be at and your chauffeur will meet you there.'),
    ('What does a black car from Blaine cost?', 'Fares start at $49 for the Lincoln Continental sedan, $59 for the Mercedes-Benz S-Class executive sedan and $69 for the Cadillac Escalade SUV, plus distance. Long-distance trips to Duluth, St. Cloud or Rochester are quoted as one flat fare before you confirm.'),
    ('Can you move a whole team or a group of golfers?', 'Yes. Each Escalade seats six with bags, and for larger groups we dispatch two or three vehicles together under one booking so everyone leaves and arrives at the same time. Tell dispatch the headcount and the amount of gear and we will plan the fleet.'),
    ('Are early flights and round trips available from Blaine?', 'Yes. Dispatch is staffed 24 hours a day, so pre-dawn pickups are routine, and booking your departure and return together saves 10 percent on the total. Book online at least two hours ahead or call for anything sooner.'),
  ],
  related=[R['area'], R['black'], R['group'], R['p2p']],
  cta_h2='Book your Blaine ride',
  cta_p='Tournament weekend, tee time or 5 AM flight, a flat fare and a chauffeur who is already outside.',
  city='Blaine', city_state='MN', drive_time='about 35 minutes',
),

# ---------------------------------------------------------------- Stillwater
dict(
  file='car-service-stillwater.html',
  title='Black Car Service in Stillwater, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Stillwater Car Service',
  meta='Private black car service in Stillwater, MN. Flat fares to MSP in about 45 minutes, downtown and St. Croix Valley pickups, winery days by the hour and 24/7 dispatch.',
  keywords='Stillwater car service, Stillwater black car service, Stillwater airport car service, Stillwater to MSP, chauffeur Stillwater MN, St. Croix Valley car service',
  service_type='Black car service',
  eyebrow='Stillwater · St. Croix Valley · MSP in 45 min',
  h1='Black Car Service in <span class="gold-text">Stillwater, MN</span>',
  lede='Chauffeured rides between the St. Croix Valley, MSP and the Twin Cities, with a flat fare and a chauffeur who knows Main Street.',
  image='images/site/city-stillwater.webp',
  image_alt='Black Mercedes-Benz S-Class parked on Main Street in downtown Stillwater with the historic lift bridge and St. Croix River behind',
  image_caption='Stillwater · Main Street · River Valley',
  image_prompt=SCLASS + ' parallel-parked at the curb on a historic riverside main street of nineteenth-century brick and limestone storefronts in downtown Stillwater, Minnesota, with an old steel vertical-lift bridge and the wide St. Croix River visible at the end of the street, on a warm October afternoon with the bluffs across the river in full orange and red color. A couple in their fifties dressed for dinner, both facing the camera and smiling, step out of the rear passenger door onto the sidewalk, front-hinged door open. ' + PHOTO_END,
  intro_eyebrow='Serving Stillwater',
  intro_h2='The birthplace of Minnesota, 45 minutes from the terminal',
  intro=[
    'Stillwater is a weekend town, a wedding town and a place people move to for the river, and none of those things are easy to reach by rideshare app when you need to be at the airport at dawn. We pick up throughout the city, from the historic downtown along Main Street and Lowell Park to the neighborhoods on the hill, the inns and boutique hotels near the river, and the newer streets off Highway 36 and Manning Avenue. Your chauffeur takes Highway 36 west to I-694 and reaches MSP in about 45 minutes.',
    'Visitors book us from MSP and downtown Minneapolis to the Lora, the Water Street Inn and the bed and breakfasts in the old lumber baron houses, and back again after a weekend of shops, riverboats and the walk across the old lift bridge. Locals use us for early flights, for evenings in Minneapolis and Saint Paul, and for appointments at Lakeview Hospital and the clinics in Woodbury. Corporate travelers visiting the manufacturing and window-making campuses in the valley use us for the airport run at both ends.',
    'Wine country begins on the edge of town. Book the hourly service with a three-hour minimum and your chauffeur will take your party to Saint Croix Vineyards, the wineries near Dellwood and the tasting rooms in Wisconsin across the river, and bring everyone home safely.',
  ],
  bullets_eyebrow='Why Stillwater rides with us',
  bullets_h2='What you get on every Stillwater pickup',
  bullets=[
    ('Flat fare, quoted first', 'Stillwater to MSP is quoted as one fixed fare before you confirm, no meter and no surge on a busy Lumberjack Days or fall color weekend.'),
    ('Downtown and the hill', 'We know Main Street, the narrow streets up the bluff and the inn entrances near Lowell Park, and your chauffeur waits at the right door.'),
    ('Winery days by the hour', 'Hourly service with a three-hour minimum covers Saint Croix Vineyards, the Dellwood wineries and tasting rooms across the river, quoted at booking.'),
    ('Flight-tracked airport runs', 'Departures leave Stillwater on time and returns wait for a late landing at MSP, so the ride back to the river is never rushed.'),
  ],
  faq=[
    ('How long is the ride from Stillwater to MSP Airport?', 'About 45 minutes in normal traffic, west on Highway 36 to I-694 and I-494 or through Saint Paul on I-94 and Highway 5. Weekday rush hour and winter weather can add time, so we schedule your pickup with a cushion and track your flight.'),
    ('Do you pick up at downtown Stillwater hotels and inns?', 'Yes. We serve every address in Stillwater and the St. Croix Valley, including the Lora Hotel, the Water Street Inn, the historic bed and breakfasts on the hill, Lakeview Hospital and homes off Highway 36 and Manning Avenue. Tell us the entrance and your chauffeur will be there.'),
    ('What does a black car from Stillwater cost?', 'Fares start at $49 for the Lincoln Continental sedan, $59 for the Mercedes-Benz S-Class executive sedan and $69 for the Cadillac Escalade SUV, plus distance. Longer trips such as Rochester, Duluth or St. Cloud are quoted as one flat fare before you confirm.'),
    ('Can I book a winery tour from Stillwater?', 'Yes. Hourly service has a three-hour minimum and the rate is quoted at booking. Your chauffeur stays with your party for the whole afternoon, waits at each vineyard and tasting room, and brings everyone back to Stillwater or the Twin Cities safely.'),
    ('Do you handle early morning flights and round trips?', 'Yes. Dispatch answers 24 hours a day, so a 4 AM pickup in Stillwater is routine. Booking your departure and return together saves 10 percent, and if the return flight changes you tell dispatch and we retime the pickup at no charge.'),
  ],
  related=[R['area'], R['black'], R['wine'], R['hourly']],
  cta_h2='Stillwater to anywhere, quoted flat',
  cta_p='Airport runs, city nights and winery afternoons from the St. Croix Valley. Book online or call dispatch any hour.',
  city='Stillwater', city_state='MN', drive_time='about 45 minutes',
),

# ---------------------------------------------------------------- Rochester
dict(
  file='car-service-rochester.html',
  title='Black Car Service in Rochester, MN | Mayo Clinic & MSP Rides | Total Town Car Service',
  title_short='Rochester Car Service',
  meta='Private black car service between Rochester, MN, Mayo Clinic and MSP Airport. Flat long-distance fares quoted before you confirm, winter-ready SUV and 24/7 dispatch.',
  keywords='Rochester MN car service, Rochester black car service, Rochester to MSP car service, Mayo Clinic car service, chauffeur Rochester MN, MSP to Rochester',
  service_type='Black car service',
  eyebrow='Rochester · Mayo Clinic · MSP in 90 min',
  h1='Black Car Service in <span class="gold-text">Rochester, MN</span>',
  lede='Private, direct rides between Rochester, Mayo Clinic and MSP Airport, with one flat fare quoted before you confirm.',
  image='images/site/city-rochester.webp',
  image_alt='Black Cadillac Escalade parked at the curb outside a glass medical building in downtown Rochester, Minnesota, in winter',
  image_caption='Rochester · Mayo Clinic · Flat Fare',
  image_prompt=ESCALADE + ' parallel-parked at the curb on a downtown street in Rochester, Minnesota, outside a tall modern glass-and-granite medical building with an enclosed skyway crossing the street overhead, on a bright cold January morning with light snow on the sidewalk edges. An elderly couple in warm winter coats, both facing the camera and smiling warmly, step out of the rear passenger door onto the cleared sidewalk, the husband offering his wife his arm, front-hinged door open, a chauffeur in a dark suit holding the door and smiling toward the camera. ' + PHOTO_END,
  intro_eyebrow='Serving Rochester',
  intro_h2='Twin Cities to Mayo Clinic, private and direct',
  intro=[
    'Rochester is about 85 miles south of the Twin Cities on Highway 52, roughly 90 minutes door to door, and it is the long-distance trip we make more than any other. Most of our Rochester rides begin or end at Mayo Clinic, at the Gonda Building, the Mayo Building and the Plummer Building downtown, at the Saint Marys campus on the west side, or at the hotels tied into the downtown skyway system, including the Kahler Grand, the Hilton and the Marriott. We also serve homes, offices and Rochester International Airport for guests arriving on regional flights.',
    'Patients and families choose a private car for this drive because it is quiet, direct and unhurried, and because the fare is a single flat number quoted before you confirm. Your chauffeur meets you at MSP baggage claim with a name sign if you want one, loads the luggage, and drives straight to your hotel or appointment entrance. Return rides are timed around your last appointment, and the round trip saves 10 percent. In winter the Cadillac Escalade is the right choice for Highway 52.',
    'We also handle the reverse trip for Rochester residents flying out of MSP, executives visiting the companies along the Highway 52 corridor, and events at the Mayo Civic Center. Hourly and as-directed service stays within the Twin Cities metro, so Rochester trips are always quoted point to point.',
  ],
  bullets_eyebrow='Why Rochester rides with us',
  bullets_h2='What you get on every Rochester trip',
  bullets=[
    ('One flat long-distance fare', 'MSP or the Twin Cities to Mayo Clinic, your hotel or any Rochester address, quoted as a single number before you confirm.'),
    ('Mayo Clinic entrances, known', 'Your chauffeur knows the Gonda Building, Saint Marys, Methodist and the skyway hotels, and drops you at the door you actually need.'),
    ('Winter-ready SUV', 'The Escalade handles Highway 52 in snow with room for six and their bags, and every chauffeur drives this route in all four seasons.'),
    ('Timed around appointments', 'Returns are scheduled for the end of your last appointment, and if the day runs long you call dispatch and we adjust the pickup.'),
  ],
  faq=[
    ('How long is the drive from Rochester to MSP Airport?', 'About 90 minutes in normal conditions, straight up Highway 52 to I-494 and the terminals. In snow or heavy traffic we allow more, and we schedule departures with enough margin for check-in and security at MSP.'),
    ('Do you pick up at Mayo Clinic and the downtown Rochester hotels?', 'Yes. We serve the Gonda Building, the Mayo Building, Saint Marys and Methodist campuses, the Kahler Grand, the Hilton and Marriott near the clinic, and any other Rochester hotel, home or office. Tell us which entrance and your chauffeur will be waiting there.'),
    ('What does a car between the Twin Cities and Rochester cost?', 'Rochester trips are long-distance and are quoted as one flat fare before you confirm, based on the vehicle you choose. Sedan fares start at $49, the S-Class at $59 and the Escalade at $69, plus distance, and booking the round trip saves 10 percent.'),
    ('Can you meet an arriving patient at MSP with a name sign?', 'Yes. Meet and Greet is $15. Your chauffeur waits at baggage claim with a name sign, helps with luggage and mobility needs, and walks with you to the car. We track the flight, so a delayed landing costs nothing and the chauffeur is still there when you arrive.'),
    ('Can I book hourly service in Rochester?', 'Hourly and as-directed service stays within the Twin Cities metro. Rochester rides are quoted point to point, and multiple stops on the way, such as a pharmacy or a second hotel, can be added for $15 each when you book.'),
  ],
  related=[R['area'], R['mayo'], R['p2p'], R['black']],
  cta_h2='Book your Rochester ride',
  cta_p='One flat fare, one chauffeur, straight to Mayo Clinic or the terminal. Dispatch answers 24 hours a day.',
  city='Rochester', city_state='MN', drive_time='about 90 minutes',
),

# ---------------------------------------------------------------- Duluth
dict(
  file='car-service-duluth.html',
  title='Black Car Service in Duluth, MN | MSP & North Shore Rides | Total Town Car Service',
  title_short='Duluth Car Service',
  meta='Private black car service between Duluth, MN and the Twin Cities. Flat long-distance fares to MSP quoted in a single number, winter-ready SUV, Canal Park and UMD pickups.',
  keywords='Duluth car service, Duluth black car service, Duluth to MSP car service, MSP to Duluth, chauffeur Duluth MN, Canal Park car service',
  service_type='Black car service',
  eyebrow='Duluth · North Shore · MSP in 2.5 hrs',
  h1='Black Car Service in <span class="gold-text">Duluth, MN</span>',
  lede='Private, direct rides between Duluth, the North Shore and MSP Airport, with one flat fare quoted before you confirm.',
  image='images/site/city-duluth.webp',
  image_alt='Black Lincoln Continental parked at the curb in Canal Park, Duluth, with the Aerial Lift Bridge and Lake Superior behind',
  image_caption='Duluth · Canal Park · Lake Superior',
  image_prompt=CONTINENTAL + ' parallel-parked at the curb on a waterfront street of converted brick warehouses in Canal Park, Duluth, Minnesota, with the tall steel Aerial Lift Bridge and the open blue expanse of Lake Superior visible behind, on a bright breezy June morning. A young couple in light jackets, both facing the camera and smiling, step out of the rear passenger door onto the sidewalk, the woman holding a weekend bag, front-hinged door open, gulls in the sky and a distant ore boat on the horizon. ' + PHOTO_END,
  intro_eyebrow='Serving Duluth',
  intro_h2='Up I-35 to the lake, with the fare settled before you leave',
  intro=[
    'Duluth is about 150 miles north of the Twin Cities, roughly two and a half hours up I-35, and for a lot of people it is the wrong length for a rental car and the wrong price for a rideshare app. We drive it every week. Our Duluth rides run to and from Canal Park and the hotels along the Lakewalk, the Fitger\'s complex, the DECC and Bayfront, the University of Minnesota Duluth campus, the Essentia and St. Luke\'s medical campuses on the hillside, and homes from Lakeside to Spirit Mountain.',
    'Families use us to get students to and from UMD at the start and end of every term, with the Escalade holding six people and all the bags. Patients coming to the Twin Cities for specialist care book us to MSP or straight to a clinic in Minneapolis or Rochester. Business travelers use us between Duluth and MSP when the regional flight does not fit the schedule, and vacationers heading to the North Shore start at the terminal and step out at their cabin on the lake.',
    'Every Duluth trip is quoted as a single flat fare before you confirm, and the round trip saves 10 percent. The Escalade is our recommendation from November through April. Hourly and as-directed service stays within the Twin Cities metro, so Duluth rides are always point to point.',
  ],
  bullets_eyebrow='Why Duluth rides with us',
  bullets_h2='What you get on every Duluth trip',
  bullets=[
    ('One flat fare, both ways', 'MSP or anywhere in the Twin Cities to Canal Park, UMD or the hillside, quoted as a single number, with the round trip 10 percent less.'),
    ('Winter-ready for I-35', 'The Cadillac Escalade handles the drive north in snow and lake-effect weather, with room for six and a full load of luggage.'),
    ('Canal Park to campus', 'Your chauffeur knows the hotels on the Lakewalk, the UMD dorms, the DECC and the Essentia campus, and drops you at the right entrance.'),
    ('Flight-tracked at MSP', 'Return trips wait for a late landing at MSP, and departures from Duluth leave with a cushion for check-in and security.'),
  ],
  faq=[
    ('How long is the ride from Duluth to MSP?', 'About two and a half hours in normal conditions, straight down I-35 to I-494 and the terminals. In winter we allow extra time, and we schedule departures from Duluth so you arrive at MSP with a comfortable margin for check-in and security.'),
    ('Do you serve Canal Park hotels, UMD and the North Shore?', 'Yes. We pick up and drop off anywhere in Duluth, including Canal Park and Lakewalk hotels, the DECC, UMD and the College of St. Scholastica, Essentia and St. Luke\'s, and continue up Highway 61 to Two Harbors and North Shore resorts on request. Just give us the address.'),
    ('What does a car between the Twin Cities and Duluth cost?', 'Duluth trips are long-distance and are quoted as one flat fare before you confirm, based on the vehicle you choose. Sedan fares start at $49, the S-Class at $59 and the Escalade at $69, plus distance, and booking both directions together saves 10 percent.'),
    ('Can I stop on the way to Duluth?', 'Yes. Extra stops are $15 each and can be added when you book, whether that is a pickup in the north metro, a stop at Tobies in Hinckley, or a second drop-off in Superior across the bridge. Hourly service stays within the Twin Cities metro, so Duluth rides are quoted point to point.'),
    ('Can you handle an early flight for a Duluth passenger?', 'Yes. Dispatch is staffed 24 hours a day, and for a morning departure from MSP we schedule a pre-dawn pickup in Duluth or, if you prefer, bring you down the night before to a hotel near the airport. Either way your chauffeur texts when the car is outside.'),
  ],
  related=[R['area'], R['p2p'], R['black'], R['airport']],
  cta_h2='Book your Duluth ride',
  cta_p='Lake Superior to the terminal in one flat fare. Book online or call dispatch any hour.',
  city='Duluth', city_state='MN', drive_time='about 2.5 hours',
),

# ---------------------------------------------------------------- St. Cloud
dict(
  file='car-service-st-cloud.html',
  title='Black Car Service in St. Cloud, MN | MSP & Chauffeur Rides | Total Town Car Service',
  title_short='St. Cloud Car Service',
  meta='Private black car service between St. Cloud, MN and the Twin Cities. Flat fares to MSP in about 75 minutes, St. Cloud State and CentraCare pickups, winter-ready SUV, 24/7 dispatch.',
  keywords='St. Cloud car service, St. Cloud black car service, St. Cloud to MSP car service, MSP to St. Cloud, chauffeur St. Cloud MN, St. Cloud State car service',
  service_type='Black car service',
  eyebrow='St. Cloud · Central Minnesota · MSP in 75 min',
  h1='Black Car Service in <span class="gold-text">St. Cloud, MN</span>',
  lede='Private, direct rides between St. Cloud and MSP Airport or the Twin Cities, with one flat fare quoted before you confirm.',
  image='images/site/city-st-cloud.webp',
  image_alt='Black Mercedes-Benz S-Class parked beside Lake George in downtown St. Cloud, Minnesota',
  image_caption='St. Cloud · Lake George · Flat Fare',
  image_prompt=SCLASS + ' parallel-parked at the curb on a tree-lined street beside a small city lake with a tall fountain and a walking path, Lake George in downtown St. Cloud, Minnesota, on a warm late-August afternoon with the low brick and granite buildings of downtown behind the water. A college-age woman with a large duffel bag over her shoulder and her father beside her, both facing the camera and smiling, step out of the rear passenger door onto the sidewalk, front-hinged door open. ' + PHOTO_END,
  intro_eyebrow='Serving St. Cloud',
  intro_h2='Central Minnesota to the terminal, 75 minutes on I-94',
  intro=[
    'St. Cloud is about 70 miles northwest of the Twin Cities on I-94, roughly 75 minutes door to door, and it is a run we make often enough to know it in every season. We pick up throughout St. Cloud, Waite Park, Sartell and Sauk Rapids, from the St. Cloud State University campus and the Herb Brooks National Hockey Center to the CentraCare hospital on the Mississippi, downtown around Lake George and the Paramount, the hotels near Crossroads Center, and the neighborhoods on both sides of the river.',
    'Students and their families are a large part of our St. Cloud work. We bring them to campus at the start of the term and to MSP at the end of it, with the Escalade carrying six people and everything from the dorm. The same goes for the College of Saint Benedict and Saint John\'s University just west of the city. Patients traveling to specialists in the Twin Cities or Rochester book us for a quiet, direct ride, and business travelers visiting the manufacturers and corporate offices along I-94 and Highway 15 use us when the drive to MSP is the only sensible way to get there.',
    'Every St. Cloud trip is quoted as a single flat fare before you confirm, and the round trip saves 10 percent. In winter the Escalade is our recommendation for I-94. Hourly and as-directed service stays within the Twin Cities metro, so St. Cloud rides are always point to point.',
  ],
  bullets_eyebrow='Why St. Cloud rides with us',
  bullets_h2='What you get on every St. Cloud trip',
  bullets=[
    ('One flat fare, quoted first', 'St. Cloud to MSP, Minneapolis or Rochester is one fixed number before you confirm, whether it is a sedan for one or an Escalade full of dorm boxes.'),
    ('Campus and hospital entrances', 'Your chauffeur knows St. Cloud State, the National Hockey Center, CentraCare and the Collegeville and St. Joseph campuses, and drops you at the door you need.'),
    ('Winter-ready SUV', 'The Cadillac Escalade handles I-94 in snow and wind with room for six and their bags, driven by chauffeurs who know the corridor.'),
    ('Timed to your flight', 'Departures leave St. Cloud with a cushion for security at MSP, and return pickups wait for a late landing at no extra cost.'),
  ],
  faq=[
    ('How long is the ride from St. Cloud to MSP Airport?', 'About 75 minutes in normal conditions, southeast on I-94 to I-494 and the terminals. Rush hour through the northwest metro and winter weather can add time, so we schedule departures with a margin for check-in and security.'),
    ('Do you pick up at St. Cloud State, CentraCare and the hotels near Crossroads?', 'Yes. We serve every address in St. Cloud, Waite Park, Sartell and Sauk Rapids, including St. Cloud State University, the Herb Brooks National Hockey Center, CentraCare St. Cloud Hospital, downtown and the hotels around Crossroads Center, plus Saint John\'s University and the College of Saint Benedict.'),
    ('What does a car between St. Cloud and the Twin Cities cost?', 'St. Cloud trips are long-distance and are quoted as one flat fare before you confirm, based on the vehicle. Sedan fares start at $49, the S-Class at $59 and the Escalade at $69, plus distance, and booking both directions together saves 10 percent.'),
    ('Can you handle a 6 AM flight out of MSP for a St. Cloud passenger?', 'Yes. Dispatch is staffed 24 hours a day, and pre-dawn pickups in St. Cloud are routine. We calculate the departure time from your flight, add a margin for I-94 conditions, and your chauffeur texts when the car is outside. Book online two hours or more ahead, or call for sooner.'),
    ('Is hourly service available in St. Cloud?', 'Hourly and as-directed service stays within the Twin Cities metro. St. Cloud rides are quoted point to point, and extra stops along the way, such as a pickup in Maple Grove or a second address in Sartell, can be added for $15 each when you book.'),
  ],
  related=[R['area'], R['p2p'], R['black'], R['airport']],
  cta_h2='Book your St. Cloud ride',
  cta_p='Campus, hospital or home to the terminal in one flat fare. Dispatch answers 24 hours a day.',
  city='St. Cloud', city_state='MN', drive_time='about 75 minutes',
),

# ---------------------------------------------------------------- Mankato
dict(
  file='car-service-mankato.html',
  title='Black Car Service in Mankato, MN | MSP & Chauffeur Rides | Total Town Car Service',
  title_short='Mankato Car Service',
  meta='Private black car service between Mankato, MN and the Twin Cities. Flat fares to MSP in about 85 minutes, Minnesota State and Mayo Clinic Health System pickups, 24/7 dispatch.',
  keywords='Mankato car service, Mankato black car service, Mankato to MSP car service, MSP to Mankato, chauffeur Mankato MN, Minnesota State Mankato car service',
  service_type='Black car service',
  eyebrow='Mankato · Southern Minnesota · MSP in 85 min',
  h1='Black Car Service in <span class="gold-text">Mankato, MN</span>',
  lede='Private, direct rides between Mankato and MSP Airport or the Twin Cities, with one flat fare quoted before you confirm.',
  image='images/site/city-mankato.webp',
  image_alt='Black Cadillac Escalade parked at the curb on the Minnesota State University campus in Mankato on graduation day',
  image_caption='Mankato · Minnesota State · Flat Fare',
  image_prompt=ESCALADE + ' parallel-parked at the curb beside a hilltop university campus of mid-century brick and limestone buildings and green lawns at Minnesota State University in Mankato, Minnesota, on a sunny May afternoon with the river valley falling away in the background. A proud family of four, the graduate daughter in a purple cap and gown between her parents and younger brother, all facing the camera and smiling, step out of the rear passenger door onto the sidewalk, front-hinged door open. ' + PHOTO_END,
  intro_eyebrow='Serving Mankato',
  intro_h2='Down Highway 169 to the river valley, with the fare fixed up front',
  intro=[
    'Mankato is about 80 miles southwest of the Twin Cities on Highway 169, roughly 85 minutes door to door, and it is the kind of trip that a rideshare app will not reliably take at 4 AM. We do. Our Mankato rides run to and from the Minnesota State University campus on the hill, Bethany Lutheran College, the Mayo Clinic Health System hospital and clinics, the event center and Old Town downtown, the hotels along Madison Avenue and Highway 22, River Hills Mall, and the neighborhoods across the river in North Mankato.',
    'Students and families book us at move-in, graduation and every break in between, with the Escalade holding six people and a semester of belongings. Executives at the corporate headquarters in North Mankato and the manufacturers along Highway 14 use us for MSP flights when the timing does not suit a drive and a parking ramp. Patients coming to the Twin Cities or Rochester for specialist care book a quiet, direct ride, and concert and hockey crowds use us between the Twin Cities and the event center downtown.',
    'Every Mankato trip is quoted as a single flat fare before you confirm, and the round trip saves 10 percent. The Escalade is our recommendation for Highway 169 in winter. Hourly and as-directed service stays within the Twin Cities metro, so Mankato rides are always point to point.',
  ],
  bullets_eyebrow='Why Mankato rides with us',
  bullets_h2='What you get on every Mankato trip',
  bullets=[
    ('One flat fare, quoted first', 'Mankato to MSP, Minneapolis or Rochester is one fixed number before you confirm, whether it is a sedan for one or an Escalade full of dorm boxes.'),
    ('Campus, hospital and downtown', 'Your chauffeur knows Minnesota State, Bethany, Mayo Clinic Health System and the event center, and drops you at the right entrance.'),
    ('Winter-ready SUV', 'The Cadillac Escalade handles Highway 169 through the valley in snow and wind, with room for six and a full load of luggage.'),
    ('Timed to your flight', 'Departures leave Mankato with a margin for security at MSP, and return pickups wait for a late landing at no extra cost.'),
  ],
  faq=[
    ('How long is the drive from Mankato to MSP Airport?', 'About 85 minutes in normal conditions, north on Highway 169 through Shakopee to I-494 and the terminals. Rush hour in the southwest metro and winter weather can add time, so we schedule departures with a margin for check-in and security.'),
    ('Do you pick up at Minnesota State University and Mayo Clinic Health System?', 'Yes. We serve every address in Mankato and North Mankato, including Minnesota State University, Bethany Lutheran College, Mayo Clinic Health System hospital and clinics, the downtown event center, River Hills Mall and the hotels along Madison Avenue and Highway 22. Tell us the entrance and your chauffeur will be there.'),
    ('What does a car between Mankato and the Twin Cities cost?', 'Mankato trips are long-distance and are quoted as one flat fare before you confirm, based on the vehicle. Sedan fares start at $49, the S-Class at $59 and the Escalade at $69, plus distance, and booking both directions together saves 10 percent.'),
    ('Can I get a pre-dawn pickup in Mankato for an early flight?', 'Yes. Dispatch is staffed 24 hours a day and early departures are routine. We set the pickup time from your flight, add a cushion for Highway 169 conditions, and your chauffeur texts when the car is outside. Book online at least two hours ahead or call for anything sooner.'),
    ('Is hourly service available in Mankato?', 'Hourly and as-directed service stays within the Twin Cities metro. Mankato rides are quoted point to point, and extra stops such as a pickup in Shakopee or a second drop-off in North Mankato can be added for $15 each when you book.'),
  ],
  related=[R['area'], R['p2p'], R['black'], R['airport']],
  cta_h2='Book your Mankato ride',
  cta_p='Campus, clinic or Old Town to the terminal in one flat fare. Dispatch answers 24 hours a day.',
  city='Mankato', city_state='MN', drive_time='about 85 minutes',
),

]
