# City page specs, batch A: Minneapolis, Saint Paul, Bloomington, Edina, Minnetonka,
# Eden Prairie, Plymouth, Maple Grove, Wayzata, Woodbury, Eagan.

R = {
 'airport':   ('airport-service.html', 'Airport Transfers', 'MSP arrivals and departures, flight-tracked.'),
 'black':     ('msp-airport-black-car-service.html', 'MSP Airport Black Car', 'Terminal-by-terminal pickup, fixed fares.'),
 'pickup':    ('airport-pickup.html', 'Airport Pickup', 'Baggage claim to your door, timed to your flight.'),
 'mpls':      ('minneapolis-car-service.html', 'Minneapolis Black Car', 'Private, pre-arranged, chauffeur-driven.'),
 'corp':      ('corporate-transportation.html', 'Corporate Travel', 'Executive rides, accounts and invoicing.'),
 'limo':      ('limousine-service-minneapolis.html', 'Limo Service', 'The chauffeured standard in an Escalade or S-Class.'),
 'hourly':    ('hourly-car-service.html', 'Hourly Car Service', 'A car and chauffeur for a block of time.'),
 'chauffeur': ('private-chauffeur-service.html', 'Private Chauffeur', 'As-directed driving for a full day.'),
 'p2p':       ('point-to-point-transportation.html', 'Point to Point', 'Door to door, one flat rate.'),
 'group':     ('group-transportation.html', 'Group Transportation', 'Multi-vehicle coordination for larger parties.'),
 'downtown':  ('downtown-minneapolis.html', 'Downtown Minneapolis', 'Hotels, stadiums, theaters, curb to door.'),
 'crew':      ('flight-crew-charter-service.html', 'Flight Crew Charter', 'Crew transport built around report times.'),
 'mayo':      ('rochester-mayo-clinic.html', 'Rochester & Mayo Clinic', 'Twin Cities to Rochester, private and direct.'),
 'chmpls':    ('chauffeur-service-minneapolis.html', 'Chauffeur Service', 'A dedicated professional, not just a ride.'),
 'moa':       ('mall-of-america-car-service.html', 'Mall of America', 'Bloomington, MOA and MSP, door to door.'),
 'area':      ('service-areas.html', 'Service Area', 'Every city we serve, with a page for each.'),
 'prom':      ('prom-homecoming.html', 'Prom & Homecoming', 'Safe, stylish rides for the big night.'),
 'concert':   ('concert-events.html', 'Concerts & Events', 'Arrive and leave without the parking.'),
 'wine':      ('wine-brewery-tours.html', 'Wine & Brewery Tours', 'A chauffeur for the whole tasting day.'),
 'contact':   ('contact.html', 'Contact', 'Dispatch answers 24/7.'),
}

PAGES = [

# ---------------------------------------------------------------- Minneapolis
dict(
  file='car-service-minneapolis.html',
  title='Black Car Service in Minneapolis, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Minneapolis Black Car Service',
  meta='Private black car service in Minneapolis, MN. Flat fares to MSP from $49, flight tracking and 24/7 dispatch for downtown, Uptown, the North Loop and the U of M.',
  keywords='Minneapolis car service, black car service Minneapolis, Minneapolis to MSP car service, chauffeur Minneapolis, downtown Minneapolis car service, Minneapolis airport transfer',
  service_type='Black car service',
  eyebrow='Minneapolis · Our Home City · MSP in 20 min',
  h1='Black Car Service in <span class="gold-text">Minneapolis, MN</span>',
  lede='Total Town Car has been driving Minneapolis since 1991. From the North Loop to Nokomis, every ride is pre-arranged, flat-rated and flight-tracked.',
  image='images/site/city-minneapolis.webp',
  image_alt='A black Cadillac Escalade parked at the curb on the Stone Arch Bridge side of the Minneapolis riverfront with the downtown skyline behind it',
  image_caption='Minneapolis · Riverfront · Skyline',
  image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb on West River Parkway in Minneapolis at golden hour, the Stone Arch Bridge and Mill District skyline behind it, a woman in a camel coat stepping out onto the sidewalk from the rear door, facing the camera and smiling. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='Our home city',
  intro_h2='Every Minneapolis neighborhood, one dependable car',
  intro=[
    'Minneapolis is where Total Town Car started, and after three decades our chauffeurs know it street by street. We pick up at the hotels along Nicollet Mall and in the North Loop, at the towers on the Mississippi riverfront, at the Guthrie and Orchestra Hall, and at homes from Linden Hills and Kenwood to Longfellow, Nokomis and Northeast. Most Minneapolis addresses reach MSP in about 20 minutes on Hiawatha Avenue or I-35W, and you will see your flat fare before you confirm.',
    'Downtown is a big part of what we do. We handle early departures from the Loews, the Hyatt Regency and the Four Seasons, game-day rides to Target Field, U.S. Bank Stadium and Target Center, and evenings at the Walker, the Orpheum and the restaurants of Eat Street and Uptown. For the University of Minnesota, we cover move-in weekends, campus visits and parents flying in for graduation, with pickups at Dinkytown and Stadium Village that take the confusion out of a one-way street grid.',
    'Corporate riders count on us for reliable transfers between Target headquarters, U.S. Bancorp Center, the IDS Center and the airport, and for hourly service when a visiting executive has four meetings across the city in one afternoon. Whatever the trip, the car arrives early, the chauffeur helps with bags, and dispatch answers the phone at any hour. Book a round trip and save 10 percent on the pair.',
  ],
  bullets_eyebrow='What we drive in Minneapolis',
  bullets_h2='Typical Minneapolis rides',
  bullets_lede='Airport runs, downtown nights, campus weekends and business days across the city.',
  bullets=[
    ('Airport transfers from Minneapolis', 'Door to Terminal 1 or Terminal 2 in about 20 minutes from most neighborhoods, with your inbound flight tracked so a delay never costs you the ride.'),
    ('Downtown and the riverfront', 'Hotels on Nicollet Mall, the North Loop, the Mill District and the Stone Arch Bridge area, with a chauffeur who knows the skyway-level pickup spots.'),
    ('Corporate and healthcare', 'Executive rides to Target Plaza, the IDS Center and the Wells Fargo towers, plus appointments at Abbott Northwestern, HCMC and the University of Minnesota Medical Center.'),
    ('Nights out and occasions', 'Target Field, U.S. Bank Stadium, the Orpheum, First Avenue and Uptown dinners, with a car waiting when the show ends instead of a parking ramp.'),
  ],
  faq=[
    ('How long does it take to get from Minneapolis to MSP Airport?', 'About 20 minutes from downtown and most south and central Minneapolis neighborhoods, a little longer from the far north side. We build in a cushion for rush hour on I-35W and Hiawatha so you arrive at the terminal with time to spare.'),
    ('Do you pick up at downtown Minneapolis hotels?', 'Yes. We serve every downtown hotel, including the Loews, Hyatt Regency, Four Seasons, the Marquette, the Hewing and the W Foshay. Tell us the hotel and your chauffeur will be at the main entrance, or at the valet lane where the hotel prefers it.'),
    ('What does a black car from Minneapolis to the airport cost?', 'Fares from Minneapolis start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. You see the exact flat fare before you confirm and it never surges.'),
    ('Can you handle a 4 AM pickup in Minneapolis?', 'Absolutely. Early flights are a large share of our Minneapolis work. Book online at least two hours ahead or call dispatch, and the chauffeur will be at your door before the scheduled time, with a text when the car arrives.'),
    ('Is there a discount for booking a round trip?', 'Yes. Booking your departure and your return together saves 10 percent on the pair. We track your return flight and adjust the pickup automatically if it lands early or late.'),
  ],
  related=[R['area'], R['downtown'], R['black'], R['hourly']],
  cta_h2='Book your Minneapolis black car',
  cta_p='Flat fare, flight tracking and a chauffeur who has driven this city since 1991. Reserve online or call (612) 999-5382.',
  city='Minneapolis', city_state='MN', drive_time='about 20 minutes',
),

# ---------------------------------------------------------------- Saint Paul
dict(
  file='car-service-saint-paul.html',
  title='Black Car Service in Saint Paul, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Saint Paul Black Car Service',
  meta='Private black car service in Saint Paul, MN. Flat fares to MSP from $49, flight tracking and 24/7 dispatch for downtown, Summit Avenue and the Capitol.',
  keywords='Saint Paul car service, St Paul black car service, St Paul to MSP car service, chauffeur Saint Paul, downtown St Paul car service, Saint Paul airport transfer',
  service_type='Black car service',
  eyebrow='Saint Paul · Capital City · MSP in 15 min',
  h1='Black Car Service in <span class="gold-text">Saint Paul, MN</span>',
  lede='The capital city is closer to MSP than most people realize. Total Town Car gets you from Summit Hill, Highland Park or downtown to your terminal in about 15 minutes, at a fare you see up front.',
  image='images/site/city-saint-paul.webp',
  image_alt='A black Mercedes-Benz S-Class sedan parked at the curb on Summit Avenue in Saint Paul with the Cathedral of Saint Paul dome in the distance',
  image_caption='Saint Paul · Summit Avenue · Cathedral Hill',
  image_prompt='a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) parallel-parked at the curb on Summit Avenue in Saint Paul in early autumn, oaks in orange leaf and Victorian brick mansions along the boulevard, the copper dome of the Cathedral of Saint Paul down the avenue, a man in a navy suit stepping out onto the sidewalk from the rear door, three-quarter view, smiling. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The capital city',
  intro_h2='Saint Paul rides, from the Capitol to the airport',
  intro=[
    'Saint Paul sits just up the river from MSP, and from Highland Park, Macalester-Groveland or the West Seventh corridor the drive to Terminal 1 is often 15 minutes on Shepard Road and Highway 5. We pick up downtown at the Saint Paul Hotel, the InterContinental, the DoubleTree and the Hyatt Place near the Xcel Energy Center, along the grand homes of Summit Avenue and Crocus Hill, and out to Como, Payne-Phalen, Dayton\'s Bluff and the East Side.',
    'A lot of our Saint Paul work is built around institutions. Legislators, lobbyists and agency staff use us for the Capitol complex and the Minnesota History Center. Families flying in for a Macalester, Hamline, Saint Thomas or Concordia visit book a car from baggage claim to campus. Patients and visiting physicians ride to Regions Hospital, United Hospital and Children\'s Minnesota. And when the Wild are at home or the Ordway has a show, we bring you to the door on Kellogg Boulevard and back again without a ramp in sight.',
    'Every Saint Paul ride is a flat fare quoted before you confirm, with flight tracking on airport runs and a complimentary wait of 30 minutes after a domestic landing. Ask about hourly service if you are hosting guests for a Grand Avenue afternoon or a Lowertown evening, and book the departure and the return together to save 10 percent on the pair.',
  ],
  bullets_eyebrow='What we drive in Saint Paul',
  bullets_h2='Typical Saint Paul rides',
  bullets_lede='A short hop to MSP, plus everything the capital city does best.',
  bullets=[
    ('Airport transfers from Saint Paul', 'Fifteen to twenty minutes to MSP from most neighborhoods via Shepard Road, Highway 5 or I-35E, flight-tracked both directions and priced before you leave the house.'),
    ('Downtown, Lowertown and Grand Avenue', 'Rides between the Saint Paul Hotel, Rice Park, Lowertown restaurants and the boutiques of Grand Avenue, with a chauffeur who knows the one-way grid downtown.'),
    ('Capitol, campuses and hospitals', 'The State Capitol complex, Regions and United hospitals, and the Macalester, Saint Thomas, Hamline and Concordia campuses, all on a flat rate.'),
    ('Wild games, the Ordway and the State Fair', 'Drop at the Xcel Energy Center or Ordway door and a car ready when it ends, plus Fair-season rides to Como that skip the shuttle lots.'),
  ],
  faq=[
    ('How far is Saint Paul from MSP Airport?', 'Closer than you might think. Highland Park and the West Seventh area reach Terminal 1 in about 15 minutes, downtown and Summit Hill in 15 to 20, and the East Side in about 25. We plan around I-35E and Highway 5 traffic so the timing holds.'),
    ('Do you pick up at the Saint Paul Hotel and other downtown hotels?', 'Yes, every downtown hotel including the Saint Paul Hotel on Rice Park, the InterContinental on Kellogg, the DoubleTree, the Hyatt Place and the Embassy Suites. Your chauffeur meets you at the entrance and loads the bags.'),
    ('What do fares from Saint Paul to the airport start at?', 'Fares from Saint Paul start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class and $69 in a Cadillac Escalade, plus distance. The quote you see when you book is the flat fare you pay, with no surge pricing.'),
    ('Can I book a car to the Capitol or a state agency office?', 'Of course. We serve the Capitol complex, the Minnesota Senate and House office buildings, the Department of Revenue and other agency buildings regularly, and can set up an account with invoicing for firms that need rides throughout the session.'),
    ('Do you do early morning pickups in Saint Paul?', 'Yes, at any hour. Dispatch runs 24/7, and a 4:30 AM pickup in Mac-Groveland or Como is routine for us. Book online two hours or more in advance, or call for anything sooner.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Book your Saint Paul black car',
  cta_p='Fifteen minutes to MSP, one flat fare, a chauffeur at your door. Reserve online or call (612) 999-5382.',
  city='Saint Paul', city_state='MN', drive_time='about 15 minutes',
),

# ---------------------------------------------------------------- Bloomington
dict(
  file='car-service-bloomington.html',
  title='Black Car Service in Bloomington, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Bloomington Black Car Service',
  meta='Private black car service in Bloomington, MN. Ten minutes to MSP, flat fares from $49 and flight tracking for Mall of America, I-494 hotels and Normandale Lake.',
  keywords='Bloomington car service, black car service Bloomington MN, Bloomington to MSP car service, Mall of America hotel car service, I-494 hotel airport transfer, chauffeur Bloomington',
  service_type='Black car service',
  eyebrow='Bloomington · MOA & Hotel Corridor · MSP in 10 min',
  h1='Black Car Service in <span class="gold-text">Bloomington, MN</span>',
  lede='Bloomington is the closest city to MSP, and Total Town Car covers it end to end, from the Mall of America hotels to the office parks at Normandale Lake and the neighborhoods west of France Avenue.',
  image='images/site/city-bloomington.webp',
  image_alt='A black Lincoln Continental sedan parked at the curb outside a modern Bloomington hotel near Mall of America with a family stepping onto the sidewalk',
  image_caption='Bloomington · Hotel Corridor · Ten Minutes to MSP',
  image_prompt='a brand-new 2026 black Lincoln Continental sedan (horizontal chrome mesh grille, full-width LED taillights, dark limousine-tinted windows) parallel-parked at the curb outside a modern glass-and-stone hotel near the Mall of America in Bloomington, Minnesota, a young family of three stepping out onto the sidewalk from the rear door facing the camera and smiling, rolling suitcases beside them, bright late-morning sun, an airplane climbing in the distant sky. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='Ten minutes from the terminal',
  intro_h2='Bloomington, the hotel corridor and MOA',
  intro=[
    'No city in the metro is closer to MSP than Bloomington, and no city keeps us busier. The hotels strung along I-494 and American Boulevard, the JW Marriott and Radisson Blu attached to the Mall of America, the Hyatt Regency, the Embassy Suites and dozens of others send guests to the airport with us every morning. Most rides reach Terminal 1 or Terminal 2 in about 10 minutes, and even at that distance you get a flat fare, a tracked flight and a chauffeur who loads the bags.',
    'West of the hotel corridor, Bloomington is an office town. We run executive transfers to the Normandale Lake office park, the Health Partners campus and the corporate buildings along France Avenue and West 78th Street, and hourly service for visiting teams that need to bounce between Bloomington, Edina and downtown Minneapolis in one day. The residential neighborhoods around Bush Lake, Hyland Hills and Oxboro are regular early-morning pickups for families and frequent flyers.',
    'Bloomington also means the Mall of America itself. Shoppers arriving from out of town, families combining MOA with a Minnesota Zoo day in nearby Apple Valley, and conference groups at the mall-side hotels all use us for door-to-door rides that avoid the ramps. If your party is larger than six, we coordinate two or three vehicles so everyone leaves together.',
  ],
  bullets_eyebrow='What we drive in Bloomington',
  bullets_h2='Typical Bloomington rides',
  bullets_lede='The shortest airport run in the Twin Cities, plus hotels, offices and the mall.',
  bullets=[
    ('Airport transfers from Bloomington', 'About 10 minutes from any Bloomington hotel or home to Terminal 1 or Terminal 2, with a 30-minute complimentary wait after your domestic landing on the return.'),
    ('Mall of America and the I-494 hotels', 'Pickups at the JW Marriott, Radisson Blu, Hyatt Regency, Embassy Suites and every property on American Boulevard and the 494 strip, timed to your flight.'),
    ('Normandale Lake and corporate campuses', 'Executive rides to the Normandale Lake towers, HealthPartners, the offices along France Avenue and West 78th, and on to downtown when the schedule moves.'),
    ('Evenings, events and larger parties', 'Dinner in Edina or Minneapolis, a night at the Chanhassen Dinner Theatres, or a family group that needs two cars leaving the hotel at once.'),
  ],
  faq=[
    ('How long is the ride from Bloomington to MSP?', 'About 10 minutes from the Mall of America hotels and the I-494 corridor, and 12 to 15 minutes from West Bloomington near Bush Lake. It is the shortest airport run in the metro, and we still track your flight and quote a flat fare.'),
    ('Do you pick up at the Mall of America hotels?', 'Yes. The JW Marriott and Radisson Blu attached to the mall, plus the Hyatt Regency, Embassy Suites, Sheraton, Hilton and every other hotel along American Boulevard and I-494. Tell us the property and your chauffeur will be at the main entrance.'),
    ('What do fares from Bloomington to the airport start at?', 'Fares from Bloomington start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class and $69 in a Cadillac Escalade, plus distance. Because the trip is short, most Bloomington airport fares stay close to those starting rates.'),
    ('Can you handle a group of eight from one hotel?', 'Yes. The Escalade seats six with bags, so for eight we dispatch two vehicles together, often an Escalade and a sedan, so the whole party arrives at the same terminal at the same time on one booking.'),
    ('Do you do early morning hotel pickups in Bloomington?', 'Every day. Dispatch runs 24/7 and a 4 AM pickup at a Bloomington hotel is one of our most common rides. Book online at least two hours ahead or call for anything sooner, and you will get a text when the car is outside.'),
  ],
  related=[R['area'], R['moa'], R['black'], R['group']],
  cta_h2='Book your Bloomington black car',
  cta_p='Ten minutes to the terminal, one flat fare, a chauffeur at the hotel door. Reserve online or call (612) 999-5382.',
  city='Bloomington', city_state='MN', drive_time='about 10 minutes',
),

# ---------------------------------------------------------------- Edina
dict(
  file='car-service-edina.html',
  title='Black Car Service in Edina, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Edina Black Car Service',
  meta='Private black car service in Edina, MN. Twenty minutes to MSP, flat fares from $49 and flight tracking for 50th & France, Southdale and every home.',
  keywords='Edina car service, black car service Edina MN, Edina to MSP car service, chauffeur Edina, 50th and France car service, Southdale Galleria car service, Edina airport transfer',
  service_type='Black car service',
  eyebrow='Edina · West Metro · MSP in 20 min',
  h1='Black Car Service in <span class="gold-text">Edina, MN</span>',
  lede='From Country Club and Morningside to Indian Hills and Braemar, Total Town Car brings a chauffeur-driven sedan or SUV to your Edina door, with the fare fixed before you confirm.',
  image='images/site/city-edina.webp',
  image_alt='A black Cadillac Escalade parked at the curb on a boutique-lined street at 50th & France in Edina with a couple stepping onto the sidewalk',
  image_caption='Edina · 50th & France · West Metro',
  image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb on a brick-paved boutique street at 50th and France in Edina, Minnesota, flower planters and cafe tables along the sidewalk, a well-dressed couple in their fifties stepping out onto the sidewalk from the rear door, facing the camera and smiling, soft spring light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The west metro standard',
  intro_h2='Edina rides that match the neighborhood',
  intro=[
    'Edina expects a certain standard, and that suits us. Our chauffeurs pick up in Country Club, Morningside, Indian Hills, Parkwood Knolls and the newer homes around Braemar, and reach MSP in about 20 minutes on Highway 62 and I-494 or Highway 100 south. Your fare is quoted flat before you book, your flight is tracked, and the car is a Lincoln Continental, a Mercedes-Benz S-Class or a Cadillac Escalade, always clean and always early.',
    'Around town, Edina revolves around a few familiar addresses. We run shopping and dinner trips to 50th & France and the Galleria, meet guests at the Westin Edina Galleria and the Residence Inn, and cover Southdale Center, Centennial Lakes and the offices along France Avenue. Medical rides are a big part of the week too, to Fairview Southdale Hospital, the Southdale medical buildings and the clinics clustered near 66th Street, with a chauffeur who waits for the appointment when you need it.',
    'Corporate riders in Edina and neighboring Bloomington use us for accounts with monthly invoicing, and families book us for the nights out, the anniversaries at a Galleria restaurant and the graduation weekends when relatives fly in and need a reliable car from baggage claim to the house. Book the departure and the return together and save 10 percent on the pair.',
  ],
  bullets_eyebrow='What we drive in Edina',
  bullets_h2='Typical Edina rides',
  bullets_lede='Airport runs, shopping districts, hospitals and evenings out across the city.',
  bullets=[
    ('Airport transfers from Edina', 'About 20 minutes from most Edina homes to Terminal 1 or Terminal 2, with your return flight tracked so the chauffeur is at baggage claim when you land.'),
    ('50th & France, the Galleria and Southdale', 'Shopping and dinner trips to the boutiques at 50th & France, the Galleria restaurants and Southdale Center, plus hotel pickups at the Westin Edina Galleria.'),
    ('Corporate and healthcare', 'Executive rides from the France Avenue offices and Centennial Lakes, and patient trips to Fairview Southdale Hospital and the Southdale medical district with waiting time available.'),
    ('Nights out and occasions', 'Anniversaries, milestone birthdays and holiday parties from Edina to downtown Minneapolis or the Chanhassen Dinner Theatres, with a car waiting when the evening ends.'),
  ],
  faq=[
    ('How long does it take to get from Edina to MSP Airport?', 'About 20 minutes from most of Edina on Highway 62 to I-494, or Highway 100 to I-494. Country Club and Morningside are on the near side; Indian Hills and the Braemar area run a few minutes longer. We add a cushion during the morning and evening commute.'),
    ('Do you serve 50th & France and the Galleria?', 'Yes, daily. We pick up and drop at the boutiques and restaurants at 50th & France, at the Galleria and Southdale Center, and at the Westin Edina Galleria and other nearby hotels. Tell us the storefront or restaurant and the chauffeur will be at the door.'),
    ('What do fares from Edina to the airport start at?', 'Fares from Edina start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. The flat fare you see when you book is the fare you pay, with no surge pricing.'),
    ('Can you take me to Fairview Southdale and wait?', 'Yes. For appointments at Fairview Southdale Hospital or the Southdale medical buildings, book a point-to-point ride each way or an hourly block so the same chauffeur waits and drives you home. Either way the price is quoted before you confirm.'),
    ('Do you handle early morning pickups in Edina?', 'Every day. A 4:30 AM pickup in Edina for a 6:30 flight is routine for us. Dispatch is available 24/7, and the chauffeur texts when the car is in your driveway.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Book your Edina black car',
  cta_p='Twenty minutes to MSP, one flat fare, a chauffeur in your driveway. Reserve online or call (612) 999-5382.',
  city='Edina', city_state='MN', drive_time='about 20 minutes',
),

# ---------------------------------------------------------------- Minnetonka
dict(
  file='car-service-minnetonka.html',
  title='Black Car Service in Minnetonka, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Minnetonka Black Car Service',
  meta='Private black car service in Minnetonka, MN. About 25 minutes to MSP, flat fares from $49 and flight tracking for Ridgedale, Opus, Cargill and every home.',
  keywords='Minnetonka car service, black car service Minnetonka MN, Minnetonka to MSP car service, chauffeur Minnetonka, Ridgedale car service, Opus business park car service, Minnetonka airport transfer',
  service_type='Black car service',
  eyebrow='Minnetonka · West Metro · MSP in 25 min',
  h1='Black Car Service in <span class="gold-text">Minnetonka, MN</span>',
  lede='Wooded lots, corporate campuses and a long drive to the airport. Total Town Car makes the Minnetonka to MSP run predictable, with the fare fixed before you confirm and your flight tracked the whole way.',
  image='images/site/city-minnetonka.webp',
  image_alt='A black Mercedes-Benz S-Class sedan parked at the curb of a wooded Minnetonka home with a businesswoman stepping onto the walkway',
  image_caption='Minnetonka · Wooded Lots · West Metro',
  image_prompt='a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) parked at the curb in front of a cedar-and-stone home on a wooded lot in Minnetonka, Minnesota, mature oaks and pines around the property and a sliver of lake through the trees, a businesswoman in a grey coat stepping out onto the sidewalk from the rear door in three-quarter view, smiling, crisp early-morning sunlight. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The west metro, done right',
  intro_h2='Minnetonka to MSP, without the guesswork',
  intro=[
    'Minnetonka is a big city of wooded lots and winding roads, and the airport is a real drive, about 25 minutes on I-494 south or Highway 62 in normal traffic and longer during the commute. That is exactly the kind of trip where a pre-arranged car earns its keep. Your chauffeur arrives early at your home near Minnetonka Boulevard, Glen Lake, Burwell or the Highway 7 corridor, loads the bags, and the fare was fixed when you booked.',
    'Business travel drives much of our Minnetonka work. The Opus business park and the Carlson Parkway towers near I-394, the Cargill headquarters campus, and the offices along Highway 169 all send executives and visiting teams to MSP with us, often on corporate accounts with monthly invoicing. We also run hourly service when a visiting group needs to move between Minnetonka, Wayzata and downtown Minneapolis across one day.',
    'Closer to home, we cover Ridgedale Center and its restaurants, the Marriott Minneapolis West and the other hotels near the I-394 and Ridgedale interchanges, and nights out on Lake Minnetonka or in the city. Families book us for early departures, for relatives arriving at baggage claim, and for the long ride to Rochester when a Mayo appointment comes up. Round trips save 10 percent.',
  ],
  bullets_eyebrow='What we drive in Minnetonka',
  bullets_h2='Typical Minnetonka rides',
  bullets_lede='Airport runs, corporate campuses, Ridgedale and evenings on the lake.',
  bullets=[
    ('Airport transfers from Minnetonka', 'About 25 minutes to MSP from most Minnetonka neighborhoods via I-494 or Highway 62, planned around the commute, with your return flight tracked to the minute.'),
    ('Ridgedale, I-394 hotels and around town', 'Pickups at Ridgedale Center, the Marriott Minneapolis West and the hotels near Carlson Parkway, plus rides to Wayzata and Excelsior for dinner on the lake.'),
    ('Corporate campuses', 'Executive transfers for Cargill, the Opus business park, the Carlson Parkway towers and the Highway 169 offices, with accounts and invoicing for teams that travel often.'),
    ('Occasions and longer trips', 'Nights out in downtown Minneapolis, anniversaries at a lakeside restaurant, and private rides to Rochester or Duluth when the trip calls for a chauffeur.'),
  ],
  faq=[
    ('How long is the drive from Minnetonka to MSP?', 'About 25 minutes in normal traffic from most of Minnetonka, using I-494 south to the airport or Highway 62 east. The morning and late-afternoon commute can add ten minutes or more, so we schedule your pickup with that in mind.'),
    ('Do you pick up at Ridgedale and the hotels near I-394?', 'Yes. We serve Ridgedale Center, the Marriott Minneapolis West, the hotels along Carlson Parkway and Wayzata Boulevard, and the Opus area every day. Give us the entrance you prefer and the chauffeur will be there.'),
    ('What do fares from Minnetonka to the airport start at?', 'Fares from Minnetonka start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. You see the flat fare before you confirm, and it does not surge with weather or traffic.'),
    ('Can you set up a corporate account for a Minnetonka company?', 'Yes. Many Minnetonka employers use us for executive and visitor transportation with a single monthly invoice, a shared booking contact and receipts for every ride. Call dispatch or use the corporate page to get started.'),
    ('Do you handle very early pickups in Minnetonka?', 'Absolutely. A 4 AM pickup for a 6 AM departure is common from the west metro. Dispatch runs 24/7, and the chauffeur texts when the car is in your driveway. Book online two hours or more ahead, or call for sooner.'),
  ],
  related=[R['area'], R['corp'], R['black'], R['hourly']],
  cta_h2='Book your Minnetonka black car',
  cta_p='A long airport run made simple. Flat fare, flight tracking and a chauffeur at the door. Call (612) 999-5382 or book online.',
  city='Minnetonka', city_state='MN', drive_time='about 25 minutes',
),

# ---------------------------------------------------------------- Eden Prairie
dict(
  file='car-service-eden-prairie.html',
  title='Black Car Service in Eden Prairie, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Eden Prairie Black Car Service',
  meta='Private black car service in Eden Prairie, MN. About 20 minutes to MSP, flat fares from $49 and flight tracking for the Golden Triangle and every home.',
  keywords='Eden Prairie car service, black car service Eden Prairie MN, Eden Prairie to MSP car service, chauffeur Eden Prairie, Golden Triangle car service, Flying Cloud Airport car service, Eden Prairie airport transfer',
  service_type='Black car service',
  eyebrow='Eden Prairie · Southwest Metro · MSP in 20 min',
  h1='Black Car Service in <span class="gold-text">Eden Prairie, MN</span>',
  lede='Eden Prairie is one of the busiest corporate cities in Minnesota, and Total Town Car keeps its executives and families moving to MSP and back on flat, flight-tracked fares.',
  image='images/site/city-eden-prairie.webp',
  image_alt='A black Lincoln Continental sedan parked at the curb outside a glass corporate office in Eden Prairie with two executives stepping onto the sidewalk',
  image_caption='Eden Prairie · Golden Triangle · Corporate Rides',
  image_prompt='a brand-new 2026 black Lincoln Continental sedan (horizontal chrome mesh grille, full-width LED taillights, dark limousine-tinted windows) parallel-parked at the curb in front of a low glass-and-steel corporate office set among ponds and prairie grass in Eden Prairie, Minnesota, a man and a woman in business attire stepping out onto the sidewalk from the rear door facing the camera and smiling, briefcases in hand, warm late-afternoon light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The southwest metro',
  intro_h2='Eden Prairie, from the office park to the terminal',
  intro=[
    'Eden Prairie packs an unusual number of headquarters into a few square miles. The Golden Triangle between Highway 169, I-494 and Valley View Road, the campuses along Flying Cloud Drive and Technology Drive, and the towers near Eden Prairie Center all rely on dependable airport transportation, and that is our specialty. From most of Eden Prairie the drive to MSP takes about 20 minutes on I-494 east, and the fare is fixed before you confirm.',
    'Corporate riders use us for the daily grind: visiting executives from baggage claim to a morning meeting, a team catching the last flight out after a site visit, hourly service to move a group between Eden Prairie, Minnetonka and downtown Minneapolis. We set up accounts with monthly invoicing so nobody is chasing receipts. We also serve Flying Cloud Airport for private aviation passengers who need a car meeting the aircraft or a transfer to MSP for a connection.',
    'Off the clock, Eden Prairie is a family city. We pick up in the neighborhoods around Staring Lake, Mitchell Lake, Bearpath and the Preserve, drop at Eden Prairie Center and the restaurants along Prairie Center Drive, and handle the evenings out, the airport runs for visiting grandparents and the occasional ride to a concert at the Xcel Energy Center or U.S. Bank Stadium.',
  ],
  bullets_eyebrow='What we drive in Eden Prairie',
  bullets_h2='Typical Eden Prairie rides',
  bullets_lede='Corporate campuses, MSP transfers, Flying Cloud and family trips.',
  bullets=[
    ('Airport transfers from Eden Prairie', 'About 20 minutes to Terminal 1 or Terminal 2 on I-494, quoted flat before you book and tracked against your flight both directions.'),
    ('Golden Triangle and corporate campuses', 'Executive rides for the headquarters along Flying Cloud Drive, Technology Drive and Valley View Road, with accounts and invoicing for companies that travel every week.'),
    ('Flying Cloud Airport and private aviation', 'A chauffeur meeting your aircraft at Flying Cloud, or a transfer between Flying Cloud and MSP when the itinerary connects through a commercial flight.'),
    ('Neighborhoods, dinners and occasions', 'Pickups around Staring Lake, Bearpath and the Preserve, dinners on Prairie Center Drive or in downtown Minneapolis, and rides to concerts and games with a car waiting after.'),
  ],
  faq=[
    ('How long does it take to get from Eden Prairie to MSP?', 'About 20 minutes from most Eden Prairie addresses via I-494 east, a little longer from the far southwest corner near Highway 212. Rush hour on 494 can slow things, so we schedule pickups with a cushion and monitor traffic before we leave.'),
    ('Do you serve the Golden Triangle and the corporate offices on Flying Cloud Drive?', 'Yes, every day. Executive transfers to and from the Golden Triangle, Technology Drive, Valley View Road and the offices near Eden Prairie Center are a core part of our work, and we can put your company on an account with one monthly invoice.'),
    ('What do fares from Eden Prairie to the airport start at?', 'Fares from Eden Prairie start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. The flat fare is shown before you confirm and does not change with traffic.'),
    ('Can you meet a private flight at Flying Cloud Airport?', 'Yes. Tell us the FBO and tail number or arrival time and the chauffeur will be at the terminal when the aircraft lands. We also run transfers between Flying Cloud and MSP for passengers connecting to a commercial flight.'),
    ('Do you do early morning pickups in Eden Prairie?', 'Every day. Dispatch runs 24/7, and 4 AM pickups for the first flights out are routine for Eden Prairie riders. Book online at least two hours ahead, or call for anything sooner.'),
  ],
  related=[R['area'], R['corp'], R['black'], R['hourly']],
  cta_h2='Book your Eden Prairie black car',
  cta_p='Twenty minutes to MSP, one flat fare, a chauffeur who knows the office parks. Reserve online or call (612) 999-5382.',
  city='Eden Prairie', city_state='MN', drive_time='about 20 minutes',
),

# ---------------------------------------------------------------- Plymouth
dict(
  file='car-service-plymouth.html',
  title='Black Car Service in Plymouth, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Plymouth Black Car Service',
  meta='Private black car service in Plymouth, MN. About 30 minutes to MSP, flat fares from $49 and flight tracking for the Highway 55 campuses and every home.',
  keywords='Plymouth car service, black car service Plymouth MN, Plymouth to MSP car service, chauffeur Plymouth MN, Plymouth airport transfer, northwest metro car service',
  service_type='Black car service',
  eyebrow='Plymouth · Northwest Metro · MSP in 30 min',
  h1='Black Car Service in <span class="gold-text">Plymouth, MN</span>',
  lede='Plymouth is a long way from MSP by Twin Cities standards. Total Town Car turns that 30-minute drive into the easiest part of your trip, with a flat fare and a chauffeur at your door.',
  image='images/site/city-plymouth.webp',
  image_alt='A black Cadillac Escalade parked at the curb beside Medicine Lake in Plymouth with a family loading bags and smiling toward the camera',
  image_caption='Plymouth · Medicine Lake · Northwest Metro',
  image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb on a quiet residential street beside Medicine Lake in Plymouth, Minnesota, calm water and a wooded shoreline behind, a family of four with two teenagers stepping out onto the sidewalk from the rear doors, all facing the camera and smiling, soft summer evening light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The northwest metro',
  intro_h2='Plymouth to MSP, planned for you',
  intro=[
    'Plymouth is one of the largest cities in the metro, and most of it sits a good 30 minutes from MSP on I-494 south or Highway 55 and I-35W. That distance is why our Plymouth riders book ahead. Your chauffeur arrives early at your home near Medicine Lake, Parkers Lake, Wayzata Boulevard or the neighborhoods off Vicksburg Lane, and the flat fare was set when you confirmed, no matter what the commute does.',
    'Plymouth is also a serious business address. The corporate campuses along Highway 55, Xenium Lane, Fernbrook Lane and the I-494 corridor bring in visiting executives every week, and many Plymouth employers keep a corporate account with us so the airport run is one less thing to arrange. We handle hourly service for teams that need to move between Plymouth, Minnetonka and downtown Minneapolis in a single day.',
    'For everyone else, we cover the hotels near I-494 and Highway 55, evenings at the Hilde Performance Center, rides to Wayzata and Lake Minnetonka for dinner, and family trips to the airport when relatives arrive at baggage claim. Book a round trip and save 10 percent on the pair, and add a Meet & Greet so arriving guests never have to hunt for the car.',
  ],
  bullets_eyebrow='What we drive in Plymouth',
  bullets_h2='Typical Plymouth rides',
  bullets_lede='A long airport run made easy, plus corporate and family trips across the city.',
  bullets=[
    ('Airport transfers from Plymouth', 'About 30 minutes to MSP from most of Plymouth, scheduled around I-494 and Highway 55 traffic, with your flight tracked and the fare fixed in advance.'),
    ('Corporate campuses on 55 and 494', 'Executive rides to the headquarters along Highway 55, Xenium Lane, Fernbrook Lane and the I-494 corridor, on accounts with monthly invoicing.'),
    ('Around town and nearby', 'The hotels near I-494 and Highway 55, the Hilde Performance Center, and dinners in Wayzata or on Lake Minnetonka, all a flat fare from your door.'),
    ('Occasions and longer trips', 'Nights out in downtown Minneapolis, concerts at Target Center, and private rides to Duluth, St. Cloud or Rochester when the trip needs a chauffeur.'),
  ],
  faq=[
    ('How long does it take to get from Plymouth to MSP Airport?', 'About 30 minutes from central Plymouth in normal traffic, via I-494 south or Highway 55 and I-35W. During the morning commute it can run closer to 40, which is why we schedule your pickup with a cushion and watch traffic before we leave.'),
    ('Do you serve the corporate campuses along Highway 55 and I-494?', 'Yes. Executive and visitor transportation for the Plymouth headquarters along Highway 55, Xenium Lane, Fernbrook Lane and the 494 corridor is a big part of our week. We can set up an account with a single monthly invoice for your company.'),
    ('What do fares from Plymouth to the airport start at?', 'Fares from Plymouth start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. You see the full flat fare before you confirm, and it never surges.'),
    ('Can you pick up my parents at MSP and bring them to Plymouth?', 'Of course. Give us their flight number and we track it, wait 30 minutes after a domestic landing at no charge, and can add a Meet & Greet with a name sign at baggage claim for $15 so they are never looking for the car.'),
    ('Do you handle early morning pickups in Plymouth?', 'Yes, at any hour. Dispatch runs 24/7 and 3:30 or 4 AM pickups for the first flights are routine from the northwest metro. Book online at least two hours in advance or call for anything sooner.'),
  ],
  related=[R['area'], R['black'], R['corp'], R['p2p']],
  cta_h2='Book your Plymouth black car',
  cta_p='Thirty minutes to MSP, one flat fare, a chauffeur in your driveway before you are ready. Reserve online or call (612) 999-5382.',
  city='Plymouth', city_state='MN', drive_time='about 30 minutes',
),

# ---------------------------------------------------------------- Maple Grove
dict(
  file='car-service-maple-grove.html',
  title='Black Car Service in Maple Grove, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Maple Grove Black Car Service',
  meta='Private black car service in Maple Grove, MN. About 30 minutes to MSP, flat fares from $49 and flight tracking for Arbor Lakes, the hospital and every home.',
  keywords='Maple Grove car service, black car service Maple Grove MN, Maple Grove to MSP car service, chauffeur Maple Grove, Arbor Lakes car service, Maple Grove airport transfer',
  service_type='Black car service',
  eyebrow='Maple Grove · Northwest Metro · MSP in 30 min',
  h1='Black Car Service in <span class="gold-text">Maple Grove, MN</span>',
  lede='Arbor Lakes, the hospital district, the corporate campuses off I-94 and the lake neighborhoods. Total Town Car covers all of Maple Grove with flat fares and flight-tracked airport runs.',
  image='images/site/city-maple-grove.webp',
  image_alt='A black Mercedes-Benz S-Class sedan parked at the curb on a main street at Arbor Lakes in Maple Grove with a woman stepping onto the sidewalk',
  image_caption='Maple Grove · Arbor Lakes · Northwest Metro',
  image_prompt='a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) parallel-parked at the curb on the main street of the Shoppes at Arbor Lakes in Maple Grove, Minnesota, brick storefronts, hanging flower baskets and a small fountain plaza, a woman in her thirties with shopping bags stepping out onto the sidewalk from the rear door facing the camera and smiling, bright midday sun. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The northwest metro',
  intro_h2='Maple Grove rides, from Arbor Lakes to the airport',
  intro=[
    'Maple Grove grew fast, and the traffic on I-94 and I-494 grew with it. From most of the city the drive to MSP is about 30 minutes in normal conditions, and it is one of the trips where a booked car with a flat fare pays off. Our chauffeurs pick up in the neighborhoods around Weaver Lake, Fish Lake, Rice Lake and Eagle Lake, along Bass Lake Road and in the newer subdivisions on the north side, and the fare was quoted before you confirmed.',
    'The center of the city is Arbor Lakes. We drop at the Shoppes at Arbor Lakes and the Fountains, meet guests at the Hilton Garden Inn, the Courtyard, the Staybridge Suites and the other hotels along Elm Creek Boulevard, and handle the dinners and date nights that end there. Maple Grove Hospital and the medical buildings around it are regular stops, as is the Boston Scientific campus and the corporate offices near I-94 and Highway 610 for visiting executives on account.',
    'Families use us for the airport, for relatives arriving at baggage claim, and for the long rides north to Duluth or St. Cloud when a chauffeur makes more sense than a rental. Whatever the trip, dispatch answers the phone at any hour, the car arrives before you expect it, and a round trip booked together saves 10 percent on the pair.',
  ],
  bullets_eyebrow='What we drive in Maple Grove',
  bullets_h2='Typical Maple Grove rides',
  bullets_lede='Airport transfers, Arbor Lakes, healthcare and corporate campuses.',
  bullets=[
    ('Airport transfers from Maple Grove', 'About 30 minutes to MSP from most Maple Grove neighborhoods via I-94 and I-494 or Highway 169, scheduled around the commute and tracked against your flight.'),
    ('Arbor Lakes and hotels', 'Pickups at the Shoppes at Arbor Lakes, the Fountains and the Hilton Garden Inn, Courtyard and Staybridge Suites along Elm Creek Boulevard.'),
    ('Healthcare and corporate campuses', 'Patient rides to Maple Grove Hospital and the medical district, and executive transfers for the Boston Scientific campus and the offices near I-94 and Highway 610.'),
    ('Occasions and longer trips', 'Nights out in downtown Minneapolis, concerts and games, and private rides north to St. Cloud or Duluth with the same chauffeur the whole way.'),
  ],
  faq=[
    ('How long is the drive from Maple Grove to MSP?', 'About 30 minutes in normal traffic from central Maple Grove via I-94 and I-494, or Highway 169 south. The weekday commute can push that toward 40 minutes, so we schedule your pickup with a cushion and check traffic before the chauffeur leaves.'),
    ('Do you pick up at the Arbor Lakes hotels?', 'Yes. We serve the Hilton Garden Inn, the Courtyard, the Staybridge Suites and every other hotel around Arbor Lakes and Elm Creek Boulevard, along with the Shoppes and the Fountains. Tell us the property and the chauffeur meets you at the entrance.'),
    ('What do fares from Maple Grove to the airport start at?', 'Fares from Maple Grove start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. The flat fare is shown before you confirm and does not change with traffic or weather.'),
    ('Can you take me to Maple Grove Hospital and wait for my appointment?', 'Yes. Book a ride each way, or an hourly block so the same chauffeur waits at Maple Grove Hospital and drives you home afterward. Either way the price is quoted at booking and there are no surprises.'),
    ('Do you handle early morning pickups in Maple Grove?', 'Every day. A 3:30 or 4 AM pickup for the first flights out is routine for us in the northwest metro. Dispatch runs 24/7, and the chauffeur texts when the car is in your driveway.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Book your Maple Grove black car',
  cta_p='Thirty minutes to MSP, one flat fare, a chauffeur at the door before dawn if you need it. Reserve online or call (612) 999-5382.',
  city='Maple Grove', city_state='MN', drive_time='about 30 minutes',
),

# ---------------------------------------------------------------- Wayzata
dict(
  file='car-service-wayzata.html',
  title='Black Car Service in Wayzata, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Wayzata Black Car Service',
  meta='Private black car service in Wayzata, MN. About 30 minutes to MSP, flat fares from $49 and flight tracking for Lake Street, Cargill and the north shore.',
  keywords='Wayzata car service, black car service Wayzata MN, Wayzata to MSP car service, chauffeur Wayzata, Lake Minnetonka car service, Hotel Landing car service, Wayzata airport transfer',
  service_type='Black car service',
  eyebrow='Wayzata · Lake Minnetonka · MSP in 30 min',
  h1='Black Car Service in <span class="gold-text">Wayzata, MN</span>',
  lede='Lake Street, the Hotel Landing, the estates along the north shore of Lake Minnetonka. Total Town Car brings a chauffeur-driven sedan or SUV to Wayzata at a fare fixed before you confirm.',
  image='images/site/city-wayzata.webp',
  image_alt='A black Cadillac Escalade parked at the curb on Lake Street in downtown Wayzata with Lake Minnetonka behind and a couple stepping onto the sidewalk',
  image_caption='Wayzata · Lake Minnetonka · North Shore',
  image_prompt='a brand-new 2026 black Cadillac Escalade (tall thin vertical LED headlights down the front corners, large mesh grille, dark limousine-tinted windows) parallel-parked at the curb on Lake Street in downtown Wayzata, Minnesota, boutique storefronts on one side and Lake Minnetonka with sailboats and the boardwalk on the other, a couple in their forties in summer evening dress stepping out onto the sidewalk from the rear door facing the camera and smiling, golden hour light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='Lake Minnetonka',
  intro_h2='Wayzata rides on the lake and to the airport',
  intro=[
    'Wayzata is a small city with a big reputation, and the people who live and stay here expect their car to be on time and their chauffeur to know the lake. We pick up along Lake Street and the boardwalk, at the Hotel Landing, in the neighborhoods above Wayzata Bay and along the north shore toward Orono and Long Lake. The drive to MSP is about 30 minutes on I-394 and I-494, and the fare is set when you book, not when you arrive.',
    'Cargill is the anchor of Wayzata business, and its headquarters campus sends executives and visitors to the airport with us regularly, often on a corporate account with monthly invoicing. The professional offices along Wayzata Boulevard and the Carlson Parkway towers in neighboring Minnetonka are part of the same run. Hourly service is popular for visiting groups who want to see the lake, have dinner in town and get back to the hotel without arranging three separate rides.',
    'The lake itself makes Wayzata a place for occasions. We handle summer evenings at the restaurants on Lake Street, dinners across the water in Excelsior, private club events and the airport runs for guests flying in for a lakeside weekend. Book a round trip and save 10 percent on the pair, or add a Meet & Greet at baggage claim.',
  ],
  bullets_eyebrow='What we drive in Wayzata',
  bullets_h2='Typical Wayzata rides',
  bullets_lede='Airport transfers, lakeside evenings and the corporate campus on the bay.',
  bullets=[
    ('Airport transfers from Wayzata', 'About 30 minutes to MSP via I-394 and I-494, scheduled around the commute, with your flight tracked and a 30-minute complimentary wait after a domestic landing.'),
    ('Lake Street and the Hotel Landing', 'Pickups at the Hotel Landing, the restaurants and shops along Lake Street, the boardwalk and the depot, plus rides around the lake to Excelsior and Orono.'),
    ('Cargill and corporate travel', 'Executive transfers for the Cargill headquarters campus and the offices along Wayzata Boulevard, with accounts and invoicing for companies that fly guests in weekly.'),
    ('Lake evenings and occasions', 'Summer dinners on the water, anniversaries, club events and weekend guests arriving at MSP for a Lake Minnetonka stay, with a car waiting when the night ends.'),
  ],
  faq=[
    ('How long is the ride from Wayzata to MSP?', 'About 30 minutes in normal traffic via I-394 east and I-494 south, or Highway 101 and I-494 from the west side of town. The afternoon commute on 394 can add ten minutes, so we build a cushion into every airport pickup.'),
    ('Do you pick up at the Hotel Landing and the Lake Street restaurants?', 'Yes. The Hotel Landing, the restaurants along Lake Street, the boardwalk and the depot area are regular stops for us. Tell us the restaurant or entrance and the chauffeur will be at the curb.'),
    ('What do fares from Wayzata to the airport start at?', 'Fares from Wayzata start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. The flat fare you see when you book is the fare you pay.'),
    ('Can you drive guests around Lake Minnetonka for an evening?', 'Yes. Hourly service with a three-hour minimum puts a car and chauffeur at your disposal for dinner in Wayzata, a stop in Excelsior and the ride back, quoted at booking. It is a favorite for visiting family and corporate guests.'),
    ('Do you handle early morning pickups in Wayzata?', 'Absolutely. Dispatch runs 24/7 and a 4 AM pickup on the north shore for a 6 AM flight is routine. Book online at least two hours ahead or call, and the chauffeur texts when the car is in your driveway.'),
  ],
  related=[R['area'], R['black'], R['hourly'], R['corp']],
  cta_h2='Book your Wayzata black car',
  cta_p='A chauffeur who knows the lake, a flat fare to MSP and a car waiting after dinner. Reserve online or call (612) 999-5382.',
  city='Wayzata', city_state='MN', drive_time='about 30 minutes',
),

# ---------------------------------------------------------------- Woodbury
dict(
  file='car-service-woodbury.html',
  title='Black Car Service in Woodbury, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Woodbury Black Car Service',
  meta='Private black car service in Woodbury, MN. About 25 minutes to MSP, flat fares from $49 and flight tracking for Woodbury Lakes, CityPlace and every home.',
  keywords='Woodbury car service, black car service Woodbury MN, Woodbury to MSP car service, chauffeur Woodbury, Woodbury Lakes car service, east metro car service, Woodbury airport transfer',
  service_type='Black car service',
  eyebrow='Woodbury · East Metro · MSP in 25 min',
  h1='Black Car Service in <span class="gold-text">Woodbury, MN</span>',
  lede='The east metro deserves the same black car the west metro gets. Total Town Car serves all of Woodbury with flat, flight-tracked fares to MSP and a chauffeur at your door.',
  image='images/site/city-woodbury.webp',
  image_alt='A black Lincoln Continental sedan parked at the curb at an outdoor shopping center in Woodbury with a mother and daughter stepping onto the sidewalk',
  image_caption='Woodbury · East Metro · Woodbury Lakes',
  image_prompt='a brand-new 2026 black Lincoln Continental sedan (horizontal chrome mesh grille, full-width LED taillights, dark limousine-tinted windows) parallel-parked at the curb on the main street of the Woodbury Lakes open-air shopping center in Woodbury, Minnesota, brick and stucco storefronts and string lights over a central plaza, a mother and her teenage daughter stepping out onto the sidewalk from the rear door facing the camera and smiling, crisp autumn afternoon light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='The east metro',
  intro_h2='Woodbury to MSP, on the east side of the river',
  intro=[
    'Woodbury is the largest city on the east side of the metro, and for most of its neighborhoods the drive to MSP is about 25 minutes on I-494 south across the Mississippi. We pick up in the subdivisions around Colby Lake, Carver Lake, Bailey Lake and Wedgewood, along Radio Drive and Valley Creek Road, and in the newer developments on the south side toward Cottage Grove. Your fare is quoted flat before you confirm, and your flight is tracked from the moment you book.',
    'Woodbury is also the commercial heart of the east metro. We drop at Woodbury Lakes, Tamarack Village and CityPlace, meet guests at the Sheraton, the Hilton Garden Inn, the Residence Inn and the other hotels off I-94 and Radio Drive, and serve the corporate offices along Hudson Road and the I-94 corridor for visiting executives on account. Woodwinds Hospital and the medical buildings around it are regular stops for patients and visiting physicians.',
    'Beyond the airport, Woodbury riders use us for nights out in downtown Saint Paul and Minneapolis, Wild games at the Xcel Energy Center, and the occasional ride to Rochester for a Mayo Clinic appointment. Whatever the trip, dispatch answers the phone at any hour, the chauffeur helps with every bag, and a round trip booked together saves 10 percent on the pair.',
  ],
  bullets_eyebrow='What we drive in Woodbury',
  bullets_h2='Typical Woodbury rides',
  bullets_lede='Airport transfers, shopping districts, corporate offices and the east metro hospitals.',
  bullets=[
    ('Airport transfers from Woodbury', 'About 25 minutes to MSP via I-494 south, planned around the I-94 and 494 commute, with your flight tracked and the fare fixed before you leave home.'),
    ('Woodbury Lakes, Tamarack Village and CityPlace', 'Shopping and dinner trips to Woodbury Lakes, Tamarack Village and CityPlace, plus hotel pickups at the Sheraton, Hilton Garden Inn and Residence Inn off I-94.'),
    ('Corporate and healthcare', 'Executive rides for the offices along Hudson Road and the I-94 corridor, and patient trips to Woodwinds Hospital and the surrounding clinics with waiting time available.'),
    ('Nights out and occasions', 'Wild games and the Ordway in Saint Paul, dinners in Minneapolis, and weekend guests arriving at MSP for a Woodbury visit, with a car waiting when the evening ends.'),
  ],
  faq=[
    ('How long does it take to get from Woodbury to MSP?', 'About 25 minutes from most of Woodbury via I-494 south across the river, or a little longer from the far east side near Afton. Rush hour on I-94 and 494 can add time, so we schedule pickups with a cushion and monitor traffic before we leave.'),
    ('Do you pick up at Woodbury Lakes and the hotels off I-94?', 'Yes. Woodbury Lakes, Tamarack Village, CityPlace and the Sheraton, Hilton Garden Inn, Residence Inn and other hotels along I-94 and Radio Drive are regular stops. Tell us the store, restaurant or hotel entrance and the chauffeur will be there.'),
    ('What do fares from Woodbury to the airport start at?', 'Fares from Woodbury start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. The flat fare is shown before you confirm and never surges.'),
    ('Do you serve the east metro beyond Woodbury?', 'Yes. We cover Oakdale, Lake Elmo, Cottage Grove, Afton, Stillwater and the rest of Washington County, and we serve Hudson, Wisconsin across the river as well. Any address east of Saint Paul is a normal ride for us.'),
    ('Do you handle early morning pickups in Woodbury?', 'Every day. A 4 AM pickup in Woodbury for a 6 AM flight is routine. Dispatch runs 24/7, and the chauffeur texts when the car is in your driveway. Book online two or more hours ahead, or call for sooner.'),
  ],
  related=[R['area'], R['black'], R['p2p'], R['hourly']],
  cta_h2='Book your Woodbury black car',
  cta_p='Twenty-five minutes to MSP, one flat fare, a chauffeur who covers the whole east metro. Reserve online or call (612) 999-5382.',
  city='Woodbury', city_state='MN', drive_time='about 25 minutes',
),

# ---------------------------------------------------------------- Eagan
dict(
  file='car-service-eagan.html',
  title='Black Car Service in Eagan, MN | Airport & Chauffeur Rides | Total Town Car Service',
  title_short='Eagan Black Car Service',
  meta='Private black car service in Eagan, MN. About 12 minutes to MSP, flat fares from $49 and flight tracking for Viking Lakes, corporate campuses and every home.',
  keywords='Eagan car service, black car service Eagan MN, Eagan to MSP car service, chauffeur Eagan, Viking Lakes car service, Eagan hotel airport transfer, south metro car service',
  service_type='Black car service',
  eyebrow='Eagan · South Metro · MSP in 12 min',
  h1='Black Car Service in <span class="gold-text">Eagan, MN</span>',
  lede='Eagan sits just across the Minnesota River from the airport. Total Town Car gets you from Viking Lakes, the corporate campuses or your driveway to the terminal in about 12 minutes, at a fare fixed up front.',
  image='images/site/city-eagan.webp',
  image_alt='A black Mercedes-Benz S-Class sedan parked at the curb at the modern Viking Lakes development in Eagan with two executives stepping onto the sidewalk',
  image_caption='Eagan · Viking Lakes · South Metro',
  image_prompt='a brand-new 2026 black Mercedes-Benz S-Class sedan (current W223 generation, dark limousine-tinted windows) parallel-parked at the curb in the Viking Lakes district of Eagan, Minnesota, a contemporary dark-glass office building, a hotel entrance and a landscaped pond with a fountain behind, two men in business casual stepping out onto the sidewalk from the rear door facing the camera and smiling, bright morning light. Photorealistic editorial photograph, natural light, shot on a full-frame camera with a 35mm lens, fine film grain. No text, no logos, no watermarks, no readable signage.',
  intro_eyebrow='Twelve minutes from the terminal',
  intro_h2='Eagan, the closest corporate city to MSP',
  intro=[
    'Eagan is a short hop from the airport, about 12 minutes on Highway 55 or I-494 across the Minnesota River, and it packs in more corporate headquarters than almost any suburb. The Thomson Reuters campus off Highway 149, the Ecolab campus near Lone Oak Road, the Blue Cross and Blue Shield of Minnesota headquarters and the offices along Yankee Doodle Road all send executives and visiting teams to MSP with us, usually on accounts with monthly invoicing.',
    'Viking Lakes has become the newest reason to visit Eagan. We drop at the Omni Viking Lakes Hotel, the restaurants and the Minnesota Vikings practice facility for game-week guests, corporate events and training camp visitors, and we cover the older hotel cluster near Highway 55 and I-494, including the Hilton Garden Inn, the Residence Inn and the Holiday Inn. Every ride gets a flat fare, a tracked flight and a chauffeur who loads the bags.',
    'Eagan is also home to a lot of frequent flyers who simply want an easy morning. We pick up in the neighborhoods around Blackhawk Lake, Thomas Lake, Lebanon Hills and the Cedar Grove district, run round trips that save 10 percent, and handle the nights out at Lebanon Hills events, the Minnesota Zoo in neighboring Apple Valley and downtown Saint Paul and Minneapolis.',
  ],
  bullets_eyebrow='What we drive in Eagan',
  bullets_h2='Typical Eagan rides',
  bullets_lede='The second-shortest airport run in the metro, plus Viking Lakes, campuses and hotels.',
  bullets=[
    ('Airport transfers from Eagan', 'About 12 minutes to Terminal 1 or Terminal 2 via Highway 55 or I-494, with a 30-minute complimentary wait after your domestic landing on the way home.'),
    ('Viking Lakes and Eagan hotels', 'Pickups at the Omni Viking Lakes Hotel and the surrounding district, plus the Hilton Garden Inn, Residence Inn and Holiday Inn near Highway 55 and I-494.'),
    ('Corporate campuses', 'Executive transfers for Thomson Reuters, Ecolab, Blue Cross and Blue Shield of Minnesota and the offices along Yankee Doodle Road, with accounts and invoicing.'),
    ('Neighborhoods, nights out and occasions', 'Pickups around Blackhawk Lake, Thomas Lake and Cedar Grove, dinners in Saint Paul or Minneapolis, and a car waiting after Wild and Vikings games.'),
  ],
  faq=[
    ('How long is the ride from Eagan to MSP?', 'About 12 minutes from north and central Eagan via Highway 55 or I-494, and 15 to 18 minutes from the south end near Lebanon Hills and Apple Valley. It is one of the shortest airport runs in the metro, and we still track your flight and quote a flat fare.'),
    ('Do you pick up at the Omni Viking Lakes Hotel?', 'Yes. The Omni Viking Lakes Hotel, the restaurants around the district and the Vikings facility for corporate and game-week events are regular stops. We also cover the Hilton Garden Inn, Residence Inn and Holiday Inn cluster near Highway 55 and I-494.'),
    ('What do fares from Eagan to the airport start at?', 'Fares from Eagan start at $49 in a Lincoln Continental sedan, $59 in a Mercedes-Benz S-Class executive sedan and $69 in a Cadillac Escalade SUV, plus distance. Because the trip is short, most Eagan airport fares stay close to those starting rates.'),
    ('Can you set up an account for the Thomson Reuters or Ecolab campus?', 'Yes. Many Eagan employers keep a corporate account with us for executive and visitor transportation, with a shared booking contact, one monthly invoice and receipts for every ride. Call dispatch or use the corporate page to get started.'),
    ('Do you handle early morning pickups in Eagan?', 'Every day. Because the airport is so close, a 4:30 AM pickup in Eagan still gets you to the terminal well before a 6 AM flight. Dispatch runs 24/7 and the chauffeur texts when the car is outside.'),
  ],
  related=[R['area'], R['black'], R['corp'], R['p2p']],
  cta_h2='Book your Eagan black car',
  cta_p='Twelve minutes to the terminal, one flat fare, a chauffeur who knows every campus in town. Reserve online or call (612) 999-5382.',
  city='Eagan', city_state='MN', drive_time='about 12 minutes',
),

]
